elastic/elastic-charts

src/lib/axes/axis_utils.test.ts
src/lib/utils/__snapshots__/dimensions.test.ts.snap
src/lib/utils/dimensions.test.ts
src/lib/utils/dimensions.ts

`computeChartDimensions` now takes in account also `titleFontSize` and the `titlePadding`. The
snapshot are updated in relation to this new behaviour. I've fixed also the tslint error on
axis_utils test.

test: fix outdated snapshot and small tslint error

---

src/components/react_canvas/axis.tsx
src/lib/axes/axis_utils.test.ts
src/lib/axes/axis_utils.ts
src/lib/series/specs.ts
src/lib/themes/theme.ts
src/stories/styling.tsx

This PR separates the grid lines from the axis ticks so that grid lines can be styled independently of tick lines.
Current the grid line styles can be customized by:
* stroke color
* stroke width
* opacity
* dash

feat(axis): draw grid lines separately from axis tick and customize style with config

---

src/components/react_canvas/axis.tsx

fixes #11 
PR #14 actually mostly addressed the original spacing gap, but there were still a couple of pixels of space between the edge of the title and the edge of the parent, but it turns out the issue wasn't the spacing computations, just that the debug rect was drawn for the wrong height :) 
This was the spacing gap before:
And now, using the right value for the debug rect:

fix(axis): use titleFontSize for debug rect for horizontal axis title

---

.storybook/webpack.config.js
src/lib/series/legend.test.ts
src/lib/series/legend.ts
src/state/chart_state.ts
src/stories/bar_chart.tsx

With this PR we fix the legend titles as the following:
- if we have a single series component with a single data series, we use the series id as legend label for that series
- if we have a single series component with multiple data series (splitting series is used),  we use their splitting value as legend label
- if we have multiple series component with single data series on each, we use their series id titles.
- if we have multiple series components with multiple data series on each (splitting series), we use their splitting value

fix: legend titles respects series ids or groups

---

src/lib/axes/axis_utils.ts
src/stories/axis.tsx

fixes #26
Previously, without the axisTitleHeight offset, multiple axes with the same position would overflow
into each other with margins less than the title height.  Also it would appear to give the chart additional padding because the axis nearest to the chart wasn't positioned correctly.
Now, the title won't overflow  into the next axis:
(Has been tested with multiple axes for each of the positions)

fix(axis): add axisTitleHeight to axis increments

---

package.json
src/lib/series/domains/x_domain.test.ts
src/lib/series/domains/x_domain.ts
src/lib/utils/commons.ts
src/state/chart_state.ts
src/state/utils.ts
src/stories/bar_chart.tsx

Min interval is used on linear scales to compute the minimum interval between two adjacent values on X axis.
It currently works using sorting the unique list of x values.
The sort function was not implemented and the x rendering was based on string comparison of numbers: `0, 1, 10, 11, 2, 3, 4, 5, 6, 7, 8, 9`
I've added a numeric ascending compare function with tests.
I've also fixed the case when we have a single x value on a barchart with linear axis

fix: add missing min interval compare function

---

.storybook/config.ts
src/components/react_canvas/axis.tsx
src/components/react_canvas/grid.tsx
src/components/react_canvas/reactive_chart.tsx
src/lib/axes/axis_utils.test.ts
src/lib/axes/axis_utils.ts
src/state/chart_state.ts
src/stories/grid.tsx
src/stories/styling.tsx

addresses #16 
Previously, we were rendering the grid lines relative to each axis in the same layer as the axis.  Now, each axis' grid lines are rendered in a separate layer just for grid lines and the coordinates for the lines are relative to the chart (instead of the axis).  This simplifies much of the positioning logic and also gives us the option to draw anything we might want onto the grid layer without affect the axes.
Also, in combination with PR #29, this fixes the issues with rendering grid lines for multiple axes with the same position (there was both overflow and spacing issues previously). 
Since we render the grid layer first, the lines render behind the chart elements:

refactor(axis/grid): render grid lines in separate layer from axis

---

src/lib/axes/canvas_text_bbox_calculator.ts
src/stories/axis.tsx

fixes #18 
tl;dr the `measureText` function returns very different results from browser to browser and also possibly within the same browser as well, especially with very small font sizes.  We employ a strategy that scales up the font, measures the text size, then divides the result with the scaling factor to get a more accurate measurement of the text width.  Labels should now render fully in Chrome (the labels remain the same in Firefox):

fix(axis): scale tick labels to fix text truncation on chrome

---

src/components/_legend.scss
src/components/legend.tsx
src/components/react_canvas/area_geometries.tsx
src/components/react_canvas/bar_geometries.tsx
src/components/react_canvas/line_geometries.tsx
src/components/react_canvas/reactive_chart.tsx
src/lib/series/rendering.ts
src/lib/series/series_utils.test.ts
src/lib/series/series_utils.ts
src/lib/themes/theme.ts
src/specs/settings.tsx
src/state/chart_state.ts
stories/interactions.tsx

This PR implements the feature (see #24) to add a hover interaction with legend items that highlights the corresponding series in the chart.  Currently, this is implemented to set the opacity of the non-highlighted series to 0.25 and the highlighted series to 1.  This renders like below:
bar series:
line series:
area series:
mixed series:
Per the discussion below, there is also a refactoring of how `specId` and `seriesKey` are associated with a Geometry.  All Geometries now have will have these properties as they are required to be able to identify a specific geometry belonging to a spec within a series.
Also, per the discussion below, as we will likely want to share some common styles across all the different geometries, while this PR only introduces the stylistic feature of changing the …

feat(legend/series): add hover interaction on legend items

---

src/lib/series/rendering.ts
src/lib/utils/scales/scale_band.ts
src/lib/utils/scales/scale_continuous.ts
src/lib/utils/scales/scales.test.ts
src/lib/utils/scales/scales.ts
stories/bar_chart.tsx

fix #21
Limit the log scale limit and computed values to 1 or -1 depending on the original domain.
Add stacked charts story examples to possibly fix kibana cross issue https://github.com/elastic/kibana/issues/12035

fix: limit log scale domain

---

CONTRIBUTING.md
README.md
package.json
wiki/consuming.md
wiki/overview.md
wiki/theming.md

With this PR I'm introducing a better `README` plus various markdown files that describes some how-tos on the charts.
I've added the following:
- `wiki/consuming.md` to describe how to use the chart library on your own project
- `wiki/overview.md` where I moved the overview from the `README`
- `wiki/theming.md` where I described briefly how to theme a chart
- `CONTRIBUTING.md` where I moved the contributing part from the `README`
I've updated the `README` with a better installation and run.
I've also updated the `package.json` moving external dependencies like EUI and it's peers as peers dependencies.

docs(wiki): add wiki pages and updated README

---

src/components/_legend.scss
src/components/_tooltip.scss
src/components/chart.tsx
src/components/legend.tsx
src/components/legend_button.tsx
src/components/tooltips.tsx
src/index.scss

This PR align the legend design to the K7 design with the toggle button is always on the bottom left of the chart.
fix #34

style(legend): align k7 design

---

src/lib/themes/theme.test.ts
src/lib/themes/theme.ts

fix #59
It also fix 2 possible mutations on the default theme

test(theme): add tests for `mergeWithDefaultTheme`

---

src/state/chart_state.test.ts
src/state/chart_state.ts

This PR adds test coverage for the chart_state functions, bringing test coverage up to nearly 100% (there is 100% coverage of functions, but still a few branches and statements not covered).  The remaining missing coverage items reveal opportunities for refactoring the `computeChart` function to be a more pure function, so they are not addressed here but are left with the hope that our idea to refactor this will also lend itself to making these remaining states easier to test (see https://github.com/elastic/elastic-charts/issues/75).
~~- [ ] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-co …

test(chart_state): fill in missing coverage

---

src/components/react_canvas/grid.tsx
src/lib/axes/axis_utils.test.ts
src/lib/axes/axis_utils.ts
src/lib/series/scales.test.ts
src/lib/themes/theme.test.ts
src/lib/themes/theme.ts

This PR fills in missing coverage for functions and branches in `axis_utils` and `series/scales`.  Going through this also revealed a few non-reachable code areas (due to impossible conditions), which were removed once it was determined that they were for sure non-reachable.  This also refactors the grid line config merge function, moving it into `theme` to be locatable along with other style-related code.

test(axis_utils,scales,theme): fill in missing coverage

---

jest.config.json
package.json
src/lib/axes/canvas_text_bbox_calculator.test.ts
src/lib/axes/canvas_text_bbox_calculator.ts
src/state/chart_state.test.ts
yarn.lock

close #90 
This PR fixes the truncation issues with formatted labels on Chrome by adding a 1px padding amount to cover any undercalculation.  This also means that we can now significantly reduce the amount that we are scaling fonts by.  It does not completely remove the need for a bit of scaling (tested just with offsetting with padding and there was still some truncation).
On Mac OS X Chrome:
Also, see #94 for enhancing this by allowing users to define more padding.
~- [ ] Unit tests were updated or added to match the most common scenarios~

fix(canvas_text_bbox_calculator): increase font scaling factor

---

src/lib/series/series.test.ts
src/lib/series/series.ts
src/lib/series/specs.ts
src/state/chart_state.test.ts
src/state/chart_state.ts
src/state/utils.test.ts
src/state/utils.ts
stories/styling.tsx

close #39 
This PR adds the ability to specify a custom series colors through a prop on the series spec.
Each series can now receive an optional prop `customSeriesColor: Map<DataSeriesColorValues, string>`, where the key is used to identify the series and the string is a representation of the color.  Under the `Stylings` section of Storyboard, there is an example of this in action.
The color picker in the legend is also still usable to customize a series color; on color picker update, the `customSeriesColor` prop for the corresponding series is updated.

feat(series): set custom series colors through spec prop

---

.storybook/webpack.config.js

The story source was missing because of the folder change introduced in e1b3ddf
fix #71

build(storybook): fix missing story source view

---

src/components/react_canvas/area_geometries.tsx
src/components/react_canvas/bar_geometries.tsx
src/components/react_canvas/globals.ts
src/components/react_canvas/line_geometries.tsx
src/components/react_canvas/reactive_chart.tsx

This PR will fix errors caused by duplicated react element keys in line and area chart.
It also move 3 global properties used on Konva elements to a global object.

fix(chart): fix duplicated keys for chart elements

---

src/components/react_canvas/reactive_chart.tsx
src/state/chart_state.test.ts
src/state/chart_state.ts

This PR add the mouseup listener on the window element at the mousedown event for bushing.
we remove it after the brush is end. 
We also disabled the tooltip when brushing.
fix #119

fix(brushing): enable mouseup event outside chart element

---

src/lib/series/legend.test.ts
src/lib/series/legend.ts
src/lib/series/series.test.ts
src/lib/series/series.ts
src/specs/specs_parser.test.tsx
src/specs/specs_parser.tsx
src/state/chart_state.test.ts
src/state/chart_state.ts
src/state/utils.test.ts
src/state/utils.ts
stories/interactions.tsx

fix #113 
This PR fixes the issue where the visibility of the data series would reset on every state change.
Previously, `resetSelectedDataSeries` was being called in `componentDidUpdate` on `SpecsParser`.  Instead of keeping track of `selectedDataSeries` (and assuming `isVisible: false` as the default), we now assume visibility as the default and keep track of `deselectedDataSeries`.  This has the advantage that we do not need to reset any kind of visibility and visibility state can be better preserved as specs are being updated & added.
- splitAccessors change
- yAccessors change
- changes in split accessor values in data
- removing a series that is the only selected visible series (this is the same as the functionality in current kibana)
Use ~~strikethroughs~~ to remove checklist items …

fix(chart_state): maintain series visibility state on props update

---

src/components/chart_resizer.tsx
src/components/react_canvas/reactive_chart.tsx

This commit correct the behaviour of using clientX and clientY instead of offsetX and offsetY. The
previous behavious used the synthetic position of the mouse cursor, this commit change it to use the
native event value that already take care of the border box.
fix #123

fix(crosshair): use offsetX/Y instead of clientX/Y

---

src/state/chart_state.ts
src/state/utils.test.ts
src/state/utils.ts

The `animateData` prop was not used. This PR reenable this functionality and add a max thresholds of bars and lines/area points before disabling automatically the animation.

fix(animation): re-enabled animateData prop to disable animation

---

src/lib/series/domains/x_domain.test.ts
src/lib/series/domains/x_domain.ts
src/lib/series/specs.ts
wiki/overview.md

This PR will limit xScaleType to linear, time and ordinal only values.
We no longer accept a log or sqrt scale type for the xScaleType props in every bar/area/line components
close #122

fix(specs): limit xScaleType to linear, time and ordinal

---

src/lib/series/legend.test.ts
src/lib/series/legend.ts
src/lib/series/specs.ts
src/lib/series/tooltip.ts
stories/area_chart.tsx
stories/bar_chart.tsx

fix #136
A `name` prop is now available for each series. This name will be used, if available, on every
legend or tooltip instead of the specId (used as fallback).
```
<BarSeries
name={'Count'}
/>
<LineSeries
name={'Count'}
/>
<AreaSeries
name={'Count'}
/>
```

feat(specs): add name to series specs

---

package.json
yarn.lock

fix #145 
Kibana CI run a type check against the libs imported. We were missing two types, that are not directly exported by the chart package but are subject to typecheck by kibana.
I've moved those dev dependencies to dependencies.
I've also updated the `EUI` dependency and fixed the right `react-konva` version.

fix(build): fix dependencies for kibana integration

---

src/components/_legend.scss
src/components/legend.tsx
src/components/legend_element.tsx
src/lib/series/legend.test.ts
src/lib/series/legend.ts
src/lib/series/series.test.ts
src/lib/series/specs.ts
src/specs/area_series.tsx
src/specs/bar_series.tsx
src/specs/basic_series.tsx
src/specs/line_series.tsx
src/state/chart_state.test.ts
src/state/test/interactions.test.ts
stories/legend.tsx

close #137 
This PR introduces a new property to the series spec `hideInLegend` which, when true, will remove the legend item from being visible in the legend list.

feat(legend): hide legend item if hideLegendItem on series spec is true

---

src/lib/utils/domain.test.ts
src/lib/utils/domain.ts
stories/bar_chart.tsx

close #135
This PR addresses the issues with the previous `scaleToExtent` logic assuming a domain with only positive values.  Now, when `scaleToExtent` is false, we return a domain dependent on whether the domain has positive or negative values.  Previously, a chart with only negative values would only see the values rendering if `scaleToExtent` was true; now even when `scaleToExtent` is false, the negative values will render.  For mixed negative & positive values, we return the original domain.

fix(domain): set domain bounds dependent on negative/positive values

---

.storybook/config.ts
src/lib/axes/axis_utils.ts
src/lib/series/domains/domain.ts
src/lib/series/domains/x_domain.test.ts
src/lib/series/domains/x_domain.ts
src/lib/series/scales.ts
src/lib/series/specs.ts
src/lib/utils/scales/scale_continuous.test.ts
src/lib/utils/scales/scale_continuous.ts
src/lib/utils/scales/scale_time.test.ts
src/lib/utils/scales/scales.ts
src/state/chart_state.timescales.test.ts
stories/scales.tsx

The `d3-scaleTime` and `d3-scaleUtc` functions, used to compute axis ticks, compute a discrete and nice rounded number of ticks on a time scale. This rounding (the start of a day, an hour, a month, a year depending on the data interval) is applied to UTC or local timezones, meaning that we cannot display a nicely rounded tick if we want to display data in a timezone different from the local or utc one. 
This PR includes a new optional prop to each series `timeZone` that can be used to configure this behaviour (default to utc).
To enable a nice rounded ticks on d3-scaleUtc on any timezone we followed this approach:
your current status:
- my local timezone is UTC+1
- Kibana, or what else, is configured to use UTC-6 as timezone.
- I want to visualize my data on that timezone, that means: if …

fix(timescale): consider timezone on axis ticks

---

src/lib/series/specs.ts
src/specs/line_annotation.tsx
src/state/annotation_utils.test.ts
src/state/annotation_utils.ts
stories/annotations.tsx

re: #150 
This PR introduces two props to LineAnnotationSpec: `hideLines` and `hideTooltips` which can be used to toggle visibility of annotation lines and their tooltips when set to true.

feat(line_annotation): add hideLines and hideTooltips props to spec

---

.storybook/preview-head.html
.storybook/theme_service.ts
.storybook/webpack.config.js

close #97
This adds a Content Security Policy to the Elastic Charts docs for testing our compatibility against a strict setup.
We are currently using the following rules:
`default-src 'self' style-src 'nonce-Pk1rZ1XDlMuYe8ubWV3Lh0BzwrTigJQ='`
The nonce is for the dynamic loading of our chart style and the EUI CSS styls - this is otherwise handled by a consuming application (Cloud, Kibana).
We currently have two main CSP broken rules that are here bacause we depends on EUI https://github.com/elastic/eui/pull/1472 :
- react-ace (inline styles)
- color picker (Refused to load the image `'<URL>'`)
- ~[ ] This was checked for cross-browser compatibility, [including a check against …

chore(csp): add CSP meta tag and nonce for styles

---

src/state/chart_state.ts

Disable animations for all charts until we fix #89 and #41 and until we found a right strategy for
animate everything nicely and at 60fps.
fix #161

fix: temporary disable animation

---

src/components/react_canvas/area_geometries.tsx
src/components/react_canvas/bar_geometries.tsx
src/components/react_canvas/line_geometries.tsx
src/components/react_canvas/utils/rendering_props_utils.test.ts
src/components/react_canvas/utils/rendering_props_utils.ts
src/lib/series/rendering.test.ts
src/lib/series/rendering.ts
src/lib/series/specs.ts
src/lib/themes/theme.ts
src/state/utils.ts
stories/styling.tsx

close #138 
This PR introduces the ability to customize the styles for a series independently from the main chart theme (which is shared across all series).  If both a custom individual series style and custom chart theme are defined, precedence will be given to the custom series style (though the chart theme can still be used to change styles for the series which do not have their own custom series styles).
Currently, this supports the same set of customizable styling options as the main chart theme, but can be extended to cover additional styles currently not implemented as customizable.
The following examples can be found under `Styling` in storybook:
currently supported customizable options:
- border stroke width
- border stroke color
- border visibility
- bars opacity (currrently not …

feat: allow individual series styling

---

src/specs/area_series.tsx
src/specs/bar_series.tsx
src/specs/line_series.tsx
stories/area_chart.tsx
stories/bar_chart.tsx
stories/line_chart.tsx

fix #158 
This PR implements the fix for the issue of SpecComponent updates not clearing the previous spec version when the update involves a specId change.  Now, we check if the specId has changed on update, and if so, remove the spec by the previous specId from the chartStore.
Before:
After:
~- [ ] Unit tests were updated or added to match the most common scenarios~

fix: remove old specs with changed ids

---

src/components/react_canvas/area_geometries.tsx
src/components/react_canvas/line_geometries.tsx
src/components/react_canvas/utils/rendering_props_utils.test.ts
src/components/react_canvas/utils/rendering_props_utils.ts
stories/mixed.tsx

There were discrepancies between the props applied to animated elements and non-animated elements.  When we disabled animation across the board, this discrepancy surface issues with the non-animated elements not having the correct transform.x applied, leading to misaligned lines & points in area and line series:
This PR applies the transform to the non-animated elements as well, resolving the alignment issues:
We also move this transform into the build props functions to require consistency in handling these values regardless of animation.

fix: apply transform.x to area & line geometries

---

src/state/utils.test.ts
src/state/utils.ts
stories/axis.tsx

This fix correct the wrong behaviour when indexed geometries are not merged on multiple series.
Previously we just rewrote the entire stacked and non stacked map. Now, for each stacked/nonstacked
series we are merging that indexed geometry map.
fix #186
**Before:**
**After:**

fix: merge multi-group indexed geometry

---

src/components/react_canvas/bar_geometries.tsx

This PR will disable the automatic removal of a border for narrow bars. We let the
user/developer decide the right size of the bar border width.
fix #189

fix(bars): remove border visibility based on bar width

---

.github/pull_request_template.md

This adds a check to the PR template checklist to ensure that any exports we want exposed to the user are exported in `src/index.ts`.
~- [ ] Unit tests were updated or added to match the most common scenarios~

chore: add check to PR template for exports

---

src/lib/axes/axis_utils.ts
src/lib/series/scales.ts
src/lib/themes/dark_theme.ts
src/lib/themes/light_theme.ts
src/lib/themes/theme.test.ts
src/lib/themes/theme.ts
src/lib/utils/commons.test.ts
src/lib/utils/commons.ts
src/lib/utils/scales/scale_band.test.ts
src/lib/utils/scales/scale_band.ts
src/lib/utils/scales/scale_continuous.test.ts
src/lib/utils/scales/scale_continuous.ts
src/lib/utils/scales/scale_time.test.ts
src/lib/utils/scales/scales.test.ts
src/lib/utils/scales/scales.ts
src/state/annotation_marker.test.tsx
src/state/annotation_utils.test.ts
src/state/chart_state.test.ts
src/state/chart_state.ts
src/state/crosshair_utils.linear_snap.test.ts
src/state/crosshair_utils.ordinal_snap.test.ts
src/state/crosshair_utils.ts
src/state/test/interactions.test.ts
src/state/utils.ts
stories/area_chart.tsx
stories/bar_chart.tsx
stories/styling.tsx

This PR will add paddings between bars clusters as shown in the screenshot 
The background highlighter width will cover the full band without padding, to be aligned with the sensible areas used for mouse interactions.
The `Theme` as a slight change on API on the `ScalesConfig` property. From:
```tsx
export interface ScalesConfig {
ordinal: {
padding: number;
};
}
```
to:
```tsx
export interface ScalesConfig {
barsPadding: number;
}
```
This to reflect the fact that: the padding is used on every scale used on X axis (linear, time or ordinal) and it's applied in the same way for bars:
```
|half padding size | bar/bars bandwidth | half padding size|
```
The padding is expressed as the proportion of the range that is reserved for blank space between bands. A value of 0 means no blank space …

feat(scales): add paddings between bars

---

.gitignore
.playground/index.html
.playground/index.tsx
.playground/playgroud.tsx
.playground/webpack.config.js
package.json
src/utils/data/formatters.ts
yarn.lock

This PR will add a simple playground that a developer can use to test rapid changes to a chart structure instead of going through storybook, add a story and develop the story inside the storybook.
You can start the playground with:
```
yarn playground
```
it will create a dev server on port 8080 by default.
the `playground.tsx` file is a simple example of chart but can be completely changed to run any chart example.
If after pulling master with this PR, changing the playground.tsx file result in a new git change please issue that command to ignore changes on that file:
```
git update-index --skip-worktree .playground/playgroud.tsx
```
- ~[ ] Any consumer-facing exports were added to `src/index.ts` …

chore: add simple playground code to run examples locally

---

.travis.yml

After switching to jenkins for PRs (https://github.com/elastic/elastic-charts/pull/174), I've also removed codecov upload from travisCI on master branch.
This commit will recover the codecov uploads from travis and enables a correct coverage check
between PRs and master
- ~[ ] …

ci(codecov): fix codecov upload on master

---

src/lib/utils/scales/scale_continuous.test.ts
src/lib/utils/scales/scale_continuous.ts

Take current offset into account when shifting ticks back into the real domain to make sure ticks are placed correctly.
~- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~

fix(scales): improve ticks for time domains spanning a DST switch

---

.playground/playgroud.tsx
src/components/legend_element.tsx

The version `4.2.2` has introduced a bug on the rendering of the legend when the eye button is clicked as displayed in the gif.
This PR fix that issue specifying the grow parameter into the title element.
- ~~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~~

fix(legend): avoid expanding label on click

---

package.json
src/index.scss
yarn.lock

This PR remove from the css build all the EUI resets and classes that where imported
through the global_syntax partials. 
The change only import the required variables and mixins.
This PR also move the babel polyfill as a dev dependency and upgrade the yarn.lock.
It also downgrade the EUI dependency to version `10.4.1` to be aligned with the Kibana 7.2 version
- ~~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~~

fix(eui): generate css without EUI classes

---

src/lib/series/specs.ts
src/state/annotation_utils.test.ts
src/state/utils.ts

Fixes #188 
In specs.ts, BasicSeriesSpec included the styles for LineSeriesSpec, AreaSeriesSpec, and BarSeriesSpec. This PR removes barSeriesStyle, lineSeriesStyle, and areaSeriesStyle from BasicSeries style and includes the SeriesStyle per each chart type. 
Included in specs.ts are the type guards for utils.ts 
```
export function isBarSeriesSpec(spec: BasicSeriesSpec): spec is BarSeriesSpec {
return spec.seriesType === 'bar';
}
export function isLineSeriesSpec(spec: BasicSeriesSpec): spec is LineSeriesSpec {
return spec.seriesType === 'line';
}
export function isAreaSeriesSpec(spec: BasicSeriesSpec): spec is AreaSeriesSpec {
return spec.seriesType === 'area';
}
```
~~-  Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & …

fix(specs):add custom style inside each specific series style

---

src/components/react_canvas/axis.tsx
src/lib/axes/axis_utils.test.ts
src/lib/axes/axis_utils.ts
src/lib/utils/__snapshots__/dimensions.test.ts.snap
src/lib/utils/dimensions.ts
stories/styling.tsx

fix #225
This PR remove the whitespace left from an undefined `title` axis spec.
The whitespace is kept if the `title` prop is any string also an empty one. Only if it's undefined, the occupied space is removed.
The `Styling->margins and paddings ` storybook story is updated with this change. Switch the show label on axis title checkboxs to add or remove the axis title from the chart configuration

fix(axis_title): remove whitespace with empty axis title

---

src/state/chart_state.ts
src/state/crosshair_utils.linear_snap.test.ts
src/state/crosshair_utils.ts
stories/bar_chart.tsx
stories/line_chart.tsx

This PR introduces a fix so that the band highlighter position appears correctly positioned when chartRotation of -90 or 180 is defined.  Previously, these flipped rotations were not being accounted for in computing the position, causing the bands to appear on the wrong side of the chart.  (This is most noticeable with series which have discontinuous data.)
Previous bug:
After implementing fix:
~- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~

fix(crosshair): adjust band position for rotation

---

package.json
src/components/chart_resizer.tsx
yarn.lock

Fix for `ChartResizer` initial render delay. A 200ms delay was applied to all initial renders.
Set debounce to `leading` to prevent initial load delay of 200ms.
Issue #109

fix(chart_resizer): debounce resize set to leading

---

src/components/_container.scss
src/components/react_canvas/reactive_chart.tsx
src/state/chart_state.test.ts
src/state/chart_state.ts

This PR adds the functionality that when `onBrushEndListener` is defined and the cursor is within the chart bounds (excluding the axes), the cursor will appear as a crosshair instead of the pointer or default.
Notice below (from Kibana Discover) that the bottom version (the original implementation) has the crosshair cursor visible to indicate to the user that the brushing is possible, while in the top version (elastic-charts version), the cursor remains the default.
This PR adds a new computed method to the chart store that checks the cursor position and `isBrushEnabled` to determine if the crosshair cursor should be visible.
~- [ ] Any consumer-facing exports were added to `src/index.ts` (and …

feat(brush): show crosshair cursor when brush enabled 

---

.playground/tsconfig.json
.playground/webpack.config.js
.storybook/tsconfig.json
.storybook/webpack.config.js
jest.config.json
package.json
src/@types/global.d.ts
src/lib/themes/theme.test.ts
src/lib/themes/theme.ts
src/lib/utils/commons.test.ts
src/lib/utils/commons.ts
src/specs/settings.test.tsx
src/specs/settings.tsx
stories/styling.tsx
tsconfig.all.json
tsconfig.jest.json
tsconfig.json
tsconfig.lib.json

Issue #201
Allow partial theme object for chart `Settings`
You can now specify a `PartialTheme` to pass to the `Settings` component where every field in the full `Theme` type is *recursively* optional.
If you wanted to change one property in a nested type lets say `left` margin we want to set to `0`. You would need to include the default/base values of `right`, `top` and `bottom` margins for those to carry over, otherwise, they will be removed!
```ts
const theme: PartialTheme = {
chartMargins: {
left: 0,
right: 10,
top: 10,
bottom: 10,
},
};
```
You *ONLY* need to include the values you want, then pass that to the `Settings` component.
```ts
const theme: PartialTheme = {
chartMargins: {
left: 0,
},
};
```
There is also no need to merge this `PartialTheme` theme using the …

feat(theme): allow recursive partial theme

---

src/components/annotation_tooltips.tsx
src/lib/series/specs.ts
src/state/annotation_utils.ts
stories/annotations.tsx

BREAKING CHANGE: this changes the type signature of `RectAnnotation.renderTooltip?` from `(position, details) => JSX.Element` to `(details) => JSX.Element`.  This allows the user to pass in a custom element without having to do the heavy lifting of writing the container positioning styles themselves.
Previously, the `renderTooltip?` property of a `RectAnnotationSpec` was used in such a way that if defined, the returned component would be used instead of the default tooltip component to render the tooltip details.  However, it was implemented in a way that required the user to also use the position information and write their own styles to position the tooltip correctly.  This lends to a not great developer user experience when the user just wants to pass a custom component (as in the …

feat(annotation): position custom rect_annotation tooltip by elastic-charts styles

---

src/lib/utils/commons.ts

Fixes type error in Kibana for `v7.0.0`

fix: type error with RecursivePartial

---

src/lib/themes/theme.ts
src/lib/utils/commons.test.ts
src/lib/utils/commons.ts

fix #253
Allow the option to merge optional partial params.

fix(theme): merge optional params

---

src/lib/series/domains/y_domain.test.ts
src/lib/series/domains/y_domain.ts
src/lib/series/legend.ts
src/lib/series/series.ts
src/lib/series/specs.ts
src/lib/series/stacked_percent_series_utils.test.ts
src/lib/series/stacked_series_utils.test.ts
src/lib/series/stacked_series_utils.ts
src/specs/bar_series.tsx
src/state/utils.ts
stories/area_chart.tsx
stories/bar_chart.tsx

This PR will add a new props that allows stacking bars, areas and lines using the percentage
mode. For each stacked x value, we scale their value to the percentage on that bucket.
That option mode is applied by groups of series (specified by `groupId`) so you need to specify only one prop on one of the group series the property: `stackAsPercentage={true}`
```tsx
<Axis 
id={getAxisId('count')} 
title="count" 
position={Position.Left} 
tickFormat={d => `${Number(d * 100).toFixed(1)}%`}/>
<AreaSeries
id={getSpecId('dataset A')}
xScaleType={ScaleType.Time}
yScaleType={ScaleType.Linear}
data={KIBANA_METRICS.metrics.kibana_os_load[1].data}
xAccessor={0}
yAccessors={[1]}
stackAccessors={[0]}
stackAsPercentage={true}
/>
<AreaSeries
id={getSpecId('dataset B')}
xScaleType={ScaleType.Time} …
```

feat(series): stack series in percentage mode

---

src/lib/axes/axis_utils.test.ts
src/lib/axes/axis_utils.ts
stories/bar_chart.tsx

This PR introduces a fix for the issue where, in histogram mode, the intermediary ticks for a time scale were not being rendered.
The issue stemmed from how the ticks were being extended in histogram mode.  Previously, we were just extending the ticks by 1 tick adding the scale's minInterval to the last computed tick.  However, in cases where the interval between ticks was smaller than the scale's minInterval, this would mean that while the last tick would be correct, there would be missing intermediary ticks between the last computed tick and the final added tick.  Now, we computed the distance between the ticks and add additional ticks with that interval until reaching the extended histogram domain end.
Before fix (note the missing ticks for the last bar):
After fix:
And additional test …

fix(ticks): fill in additional ticks for histogram

---

src/lib/series/series.ts
src/state/utils.ts
stories/bar_chart.tsx

Fix an error introduced in #250 where the last value on the legend was undefined for non stacked series.
When using the stack percentage mode, the data values are computed on a percentage scale. As we want to display the percent value and not the original value when displaying a tooltip, I've changed the place where the lastValue value is captured: from the original dataset to the formatted one.
The commit fix the the fact that the last value was computed only for stacked series.
- ~[ ] This was checked for cross-browser compatibility, [including a check against …

fix(last_value): compute last value for non stacked series

---

src/components/legend/_legend_item.scss
src/components/legend/legend_item.tsx

This PR removes the visibility button. The visibility change handling is applied on the legend item title.
**BREAKING CHANGE**: the `onLegendItemClick` click handler is no longer applied when clicking on the title. Instead a simple visibility change is applied.
Before:
After:
cc @cchaos 
I've some doubts on this because removes two important features right now:
- without the eye/eyeclosed icons we don't have a graphic representation that specify that a series is hidden. Is a ~~strikethrough~~ enough or is much more difficult to read?
- There are few legend item interaction that we need to support:
- Hide/show series (currently the only interaction on TSVB, but not an interaction on vizlib)
- click to filter (on vizlib clicking on the legend item is used to create and apply a global …

refactor(legend): remove visibility button

---

src/lib/utils/interactions.ts
src/lib/utils/scales/scale_band.test.ts
src/lib/utils/scales/scale_band.ts
src/lib/utils/scales/scale_continuous.test.ts
src/lib/utils/scales/scale_continuous.ts
src/lib/utils/scales/scales.ts
src/state/chart_state.test.ts
src/state/chart_state.ts
src/state/crosshair_utils.ts
src/state/test/interactions.test.ts
stories/bar_chart.tsx

fix #254 
This PR introduces a fix for the tooltip positioning on a chart with a single value xScale.  
I'm not entirely sure where the best place to position the tooltip, so this presents the minimal effort version, where the tooltip will be positioned inside of the chart aligned along the chart's edge (left if horizontal rotation, top if vertical rotation):
Implementation-wise, we've added a method `isSingleValue` to the `Scale` classes so that we can check if a scale is a single value scale (so that we can apply the different positioning in that case).  The `customDomain` knob was added to the stories to demonstrate that, when the chart only has one datapoint but has a multiple value scale, the tooltips are positioned as usual (since there is room to display them as normal).
Use …

fix: position tooltip within chart with single value xScale

---

src/lib/axes/axis_utils.test.ts
src/lib/series/curves.ts
src/lib/series/specs.ts
src/lib/themes/theme.ts
src/lib/utils/interactions.ts
src/lib/utils/scales/scales.ts
src/state/chart_state.ts
stories/interactions.tsx

This PR removes all the remaining `enums` on the project as babel doesn't support `const enum` directly.
The refactoring doesn't create any breaking change, just a bit more verbose code.
@emmacunningham I've also seen a problem with the `AnnotationType` , not resolved in this PR but I can work on it:
```
export const AnnotationTypes = Object.freeze({
Line: 'line' as AnnotationType,
Rectangle: 'rectangle' as AnnotationType,
Text: 'text' as AnnotationType,
});
export type AnnotationType = 'line' | 'rectangle' | 'text';
```
in this way, if you specify something like
```
const annotation = AnnotationTypes.Line
```
the type of `annotation` is `AnnotationType` and not `line` that means that if you want to do typechecking on that variable needs to go in a different way. I've fixed that behaviour …

chore: remove enums from project

---

src/lib/axes/axis_utils.ts
src/lib/series/scales.test.ts
src/lib/series/scales.ts
src/state/chart_state.ts
src/state/utils.ts
stories/annotations.tsx

fix #262 
Previously, a line annotation within a single value histogram's domain range would not appear correctly, rendering the line at the domain start position.  For example with a single value histogram with domain `3` to `4`, an annotation line at `3.5` would be rendered at `3`.  This PR adds handling for computing the x scale for a single value histogram such that the line now correctly renders in the right position:
The issue was that the annotations rely on the xScale for the x-axis position but with a single value domain, calling `xScale.scale` would return `0` for all values because the domain and range passed into the scale constructor created a scale that could not compute the right values because the domain would be single value (`[3, 3]` for our example) and the range would …

fix: adjust domain & range for single value histogram

---

src/components/react_canvas/reactive_chart.tsx
stories/interactions.tsx

This PR implements a fix for the issue of the `onElementClick` handler being called `onBrushEnd`.
(In the Discover histogram, `onElementClick` and `onBrushEnd` are defined for the chart because a bar can be clickable to set the timefilter and the brush tool can also be used to set the timefilter.  This bug causes the `onElementClick` handler to take precendence as it will be called after the `onBrushEnd` handler is called, resulting in a brush event being overridden by a click on a bar.)
Before: (note how `onElementClick` is registered after `onBrushEnd`)
After: (no `onElementClick` after `onBrushEnd`)
The source of this issue was that in the previous implementation, the `onElementClick` callback was called `onClick`; when both `onBrushEnd` and `onElementClick` are defined for a chart, …

fix: handle chart click as mouseUp to prevent click while brushing

---

src/index.ts

This PR exports  `GeometryValue` so that library consumers can use the type in type annotations (for example, when defining a `onElementClick` callback).
~- [ ] Unit tests were updated or added to match the most common scenarios~

fix: export GeometryValue so onElementClick callbacks can be typed

---

src/chart_types/xy_chart/annotations/annotation_utils.ts
src/chart_types/xy_chart/utils/specs.ts
src/components/annotation_tooltips.tsx
src/index.ts
stories/annotations.tsx

fix #278 
This PR adds a fix so that if an annotation tooltip does not have content (either because the default renderer is used and `details` is undefined or a custom formatter is being used and it returns null (for example if conditionally handling the render dependent on `details` being defined), the tooltip container doesn't still render with no content within.
This is achieved by checking if the content is defined and if not, returning null when rendering the tooltip component. 
Additionally, the type of the tooltip formatter has been changed from `(details?: string) => JSX.Element` to `(details?: string) => JSX.Element | null` to account for the formatter possibly returning null.
Now, if the tooltip has no content, nothing will render.
Use ~~strikethroughs~~ to remove checklist …

fix: disable tooltip when details or custom content is null

---

src/index.ts

Some consumers in Kibana needs this exported types. They are getting the types from the dist folder.
To avoid that I've exported those required types from the main index.ts file

fix(types): export missing types

---

.releaserc.json
package.json
yarn.lock

A slack message will be sent on the test slack channel `_test_charts_semrel` on every new package released using https://github.com/juliuscc/semantic-release-slack-bot.
The webook is created manually without using the app provided.
After a successful test I'd I will update the webhook with the correct channel
- ~[ ] Proper documentation or storybook story was added for features that …

ci: add semantic-release slack bot

---

src/components/_tooltip.scss
src/components/tooltips.tsx

Allow long series names in tooltip to wrap to next line
fix #270

fix(tooltip): fix overflow for long series names

---

.releaserc.json

Fix the semantic-release slack-bot configuration to threat the releasenote as markdown
- ~[ ] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)~

chore: configure release slack message as markdown

---

src/chart_types/xy_chart/store/chart_state.interactions.test.ts
src/chart_types/xy_chart/store/chart_state.ts

When using rotated charts, the used X and Y axis for formatting should be inverted.
fix #273

fix(tooltip): fix tooltip formatting for rotated charts

---

src/chart_types/xy_chart/legend/legend.test.ts
src/chart_types/xy_chart/legend/legend.ts

The current implementation wrongly interpret a zero value in the colorValues list of a legend item
as a single series. This cause that series to be named with the spec name or the spec id. Instead a splitted series with a group value of zero, should be threated in the same way as anyother splitted series, using the group value as the series name
fix #288
**from**
**to**
- ~[ ] Proper …

fix: handle splitted series with group value to 0

---

src/chart_types/xy_chart/store/utils.test.ts
src/chart_types/xy_chart/store/utils.ts

Each bar series needs to be shifted depending on how many bars are clustered. We don't have to shift a bar if we previously have computed a set of lines or area series.
fix #301
**before**
**after**

fix: shift bars independently from the specs order

---

src/components/legend/_legend_item.scss
src/components/legend/legend.tsx
src/components/legend/legend_item.tsx

Fix `hideInLegend` prop to work again
fix #306 -- I saw another issue for this a few weeks back but couldn't find it.

fix(legend): item hideInLegend prop

---

.playground/playgroud.tsx
src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
src/chart_types/xy_chart/crosshair/crosshair_utils.ts
src/chart_types/xy_chart/rendering/rendering.ts
src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/chart_state.ts
src/components/chart.tsx
src/specs/index.ts
src/specs/settings.test.tsx
src/specs/settings.tsx
src/utils/scales/scales.ts

Add `CursorUpdateListener` as props on `Settings` component to allow `Chart` consumer to synchronize cursors across multiple `Chart`s by calling `dispatchExternalCursorEvent` on the `Chart` ref to update cursor value.
Issue #83

feat: add cursor sync mechanism

---

src/chart_types/xy_chart/store/chart_state.ts
src/chart_types/xy_chart/utils/__snapshots__/dimensions.test.ts.snap
src/chart_types/xy_chart/utils/axis_utils.test.ts
src/chart_types/xy_chart/utils/axis_utils.ts
src/chart_types/xy_chart/utils/dimensions.test.ts
src/chart_types/xy_chart/utils/dimensions.ts
src/components/react_canvas/axis.tsx
stories/axis.tsx

This PR limit the chart dimensions to include any overflowing axis label. It consider label padding, font size, text etc.
**from:**
**to:**

fix(axis): limit chart dimensions to avoid axis labels overflow

---

stories/styling.tsx

Updating the `theme/style` story in storybook to reflect #258 changes

docs: update custom fill/stroke styles on storybook

---

.playground/index.html
src/components/chart.tsx
src/index.ts
src/utils/chart_size.test.ts
src/utils/chart_size.ts
stories/styling.tsx

fix #177 
Add multiple override types for `<Chart>` `size` props.
The `size` parameters now accept `ChartSize`:
```ts
type ChartSize = number | string | ChartSizeArray | ChartSizeObject;
type ChartSizeArray = [number | string | undefined, number | string | undefined];
type ChartSizeObject = {
width?: number | string;
height?: number | string;
}
```
The default value for an `undefined` parameter is `100%`.

feat: add chart size type overrides

---

src/components/react_canvas/area_geometries.tsx
src/components/react_canvas/line_geometries.tsx
src/components/react_canvas/utils/rendering_props_utils.test.ts
src/components/react_canvas/utils/rendering_props_utils.ts

This commit reduce the opacity of points in areas and lines series when hovering over a series in
the legend
fix #291
**from:**
**to:**

fix: reduce opacity for points when hovering over legend items

---

src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/tooltip/tooltip.test.ts
src/chart_types/xy_chart/tooltip/tooltip.ts
src/chart_types/xy_chart/utils/interactions.ts
src/chart_types/xy_chart/utils/series.ts
src/components/tooltips.tsx
stories/area_chart.tsx

A band area chart has the same seriesKey for the Y0 and Y1 values. This cause the tooltip to emit a warning because of two react components with the same key. This commit fix that adding the accessor value as part of the react key.
fix #326

fix(tooltip): fix duplicate key warning for band area charts

---

src/components/react_canvas/reactive_chart.tsx

fix #20
This PR remove the clippings from the rendered geometries to allow full rendering elements on the edges.
It moves also the axis layer 1 level below the rendered geometries to clearly visualize the elements on top of the axis lines:
cc @cchaos: FYI the following is an example with the axis layers 1 level above the chart geometries, what do you think it's better: showing the axis behind the chart elements or in front of them?:
- ~[ ] Unit tests were …

fix: remove clippings from chart

---

src/chart_types/xy_chart/annotations/annotation_marker.test.tsx
src/chart_types/xy_chart/annotations/annotation_utils.test.ts
src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
src/chart_types/xy_chart/crosshair/crosshair_utils.ordinal_snap.test.ts
src/chart_types/xy_chart/rendering/rendering.areas.test.ts
src/chart_types/xy_chart/rendering/rendering.bands.test.ts
src/chart_types/xy_chart/rendering/rendering.bars.test.ts
src/chart_types/xy_chart/rendering/rendering.lines.test.ts
src/chart_types/xy_chart/store/chart_state.interactions.test.ts
src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/utils.test.ts
src/chart_types/xy_chart/store/utils.ts
src/chart_types/xy_chart/utils/axis_utils.ts
src/chart_types/xy_chart/utils/scales.test.ts
src/chart_types/xy_chart/utils/scales.ts
src/chart_types/xy_chart/utils/specs.ts
src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
src/components/react_canvas/axis.tsx
src/utils/scales/scale_continuous.test.ts
src/utils/scales/scale_continuous.ts
src/utils/scales/scale_time.test.ts
src/utils/scales/scales.test.ts
stories/axis.tsx

This PR add the possibility to customize the number of ticks displayed on each axis.
A `ticks` parameter is added to the `Axis` component. The number specified is not always fully respected as the real number of displayed ticks because the scale function computes ticks that are uniformly spaced with human-readable values (such as multiples of powers of 10), and are guaranteed to be within the extent of the domain (see https://github.com/d3/d3-scale#continuous_ticks)

feat: customize number of axis ticks

---

src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/chart_state.ts
src/specs/settings.test.tsx

Revert default theme changes in `chart_state`

fix: default theme

---

.playground/playgroud.tsx
src/chart_types/xy_chart/annotations/annotation_utils.test.ts
src/chart_types/xy_chart/annotations/annotation_utils.ts
src/chart_types/xy_chart/utils/specs.ts
stories/annotations.tsx

This PR adds the possibility to hide the tooltip when hovering over a line annotation.
It adds a new property for the `<LineAnnotation />` component called `hideLinesTooltips`.
**NOTE**
this works correctly with horizontal charts (0 or 180 degrees) but doesn't hide the tooltip for 90,-90 degree rotated charts. That because there is an issue on detecting the mouse hover for the marker in those cases.
I'd like to merge this anyway so TSVB can have it in for 7.4
fix #324

feat: hide tooltip when hover over lines

---

src/components/_container.scss
src/components/crosshair.tsx
src/components/react_canvas/chart_container.tsx

Hide chart band when chart is empty
fix #337 
Fix `user-select` issue in safari. This was allowing the user to click and drag the chart to highlight the whole chart section.

fix(crosshair): hide band when chart is empty

---

src/specs/settings.tsx
src/utils/commons.test.ts
src/utils/commons.ts
src/utils/themes/theme.test.ts
src/utils/themes/theme.ts
stories/styling.tsx

Allow single or multiple partial themes to be passed as props to Settings component
closes #344
Take multiple `PartialThemes` and merge them into a base `Theme` in one step.
`theme` props now accepts `PartialTheme` or `PartialTheme[]`
```tsx
const EUI_OVERRIDES = {
barSeriesStyle: {
rect: {
fill: 'red',
opacity: 0.5,
},
}
const overrides = {
barSeriesStyle: {
rect: {
fill: 'blue',
},
}
render () {
<Chart>
<Settings theme={[overrides, EUI_OVERRIDES]} />
...
</Chart>
}
```
The above example will resolve to the following `PartialTheme` to be merged with the `baseTheme`.
```ts
const finalTheme = {
barSeriesStyle: {
rect: {
fill: 'blue', // color from overrides takes precedence  
opacity: 0.5,
},
}
```

feat(theme): multiple-partials

---

.playground/playgroud.tsx
src/chart_types/xy_chart/domains/y_domain.ts
src/chart_types/xy_chart/specs/area_series.tsx
src/chart_types/xy_chart/specs/axis.tsx
src/chart_types/xy_chart/specs/bar_series.tsx
src/chart_types/xy_chart/specs/histogram_bar_series.tsx
src/chart_types/xy_chart/specs/line_annotation.tsx
src/chart_types/xy_chart/specs/line_series.tsx
src/chart_types/xy_chart/specs/rect_annotation.tsx
src/chart_types/xy_chart/utils/specs.ts
src/components/react_canvas/area_geometries.tsx

fix #169, fix #185
This feature allows to compute the global Y domain on multiple groups ids.
It collect all the groupIds Y domains and extend them to the max extent.
This provide an easier way to add multiple groups but keep the same domain without need of external domain computation etc.

feat: compute global y domain on multiple groups

---

.playground/index.html
.playground/playgroud.tsx
src/chart_types/xy_chart/annotations/annotation_utils.test.ts
src/chart_types/xy_chart/annotations/annotation_utils.ts
src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
src/chart_types/xy_chart/crosshair/crosshair_utils.ts
src/chart_types/xy_chart/store/chart_state.interactions.test.ts
src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/chart_state.timescales.test.ts
src/chart_types/xy_chart/store/chart_state.ts
src/chart_types/xy_chart/utils/scales.test.ts
src/components/chart.tsx
src/components/crosshair.tsx
src/utils/scales/scale_band.ts
src/utils/scales/scale_continuous.test.ts
src/utils/scales/scale_continuous.ts
src/utils/scales/scale_time.test.ts
src/utils/scales/scales.test.ts
src/utils/scales/scales.ts
src/utils/themes/light_theme.ts
stories/interactions.tsx

fix #227, fix #221, fix #347
This commit fix the wrong behaviour of the current invertWithStep implementation.
It also fix the behaviour of cursor sync between charts with only lines and charts with only bars and empty intervals.
It finally fix also the missing line/rect annotation that are dependent on ticks to be shown. The PR removed the dependency with the ticks and allows us to place correctly the annotations depending on chart type
**Notes**
I've the impression that we need an absolute refactoring of the current scale system for linear band scales. The current implementation is a bit hacky because it's a mix of a linear scale adapted to work as a band/ordinal scale.
Right now these two scales differs by 1 pixel, it's not noticeable but it create a bit of confusion on the code and …

fix(scales): bisect correctly on continuous scales

---

.playground/playgroud.tsx
src/chart_types/xy_chart/annotations/annotation_utils.test.ts
src/chart_types/xy_chart/annotations/annotation_utils.ts
src/chart_types/xy_chart/utils/scales.ts
src/utils/scales/scale_continuous.ts

fix #342, fix #341 
This commit fix an issue where a rect annotation with x0 defined in a single value histogram, is
drawn outside the chart as shown in #341.
It also fix the tooltip rendering inside the chart: #342 
**before**
**after**
**BREAKING CHANGE**
The current coordinate configuration of a rect annotation seems inverted. From the rect annotation PR: https://github.com/elastic/elastic-charts/pull/180 I'm proposing to invert the x0 and x1 meaning on the annotation coordinate.
With `x0` I always think of the left hand side of a rectangle, and with `x1` the right hand side. 
So with that in mind I'd like to change that with 
| x0        | x1           | y0  |  y1  | render implications |
| ------------- |:-------------:|-----:|-----:|-----:|
| undefined    | undefined      | …

fix(histogram): fix annotation and tooltip overflow with single value

---

.playground/index.html
.playground/playgroud.tsx
src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
src/chart_types/xy_chart/crosshair/crosshair_utils.ts

If the xDomain doesn't cover a full interval on the min or max edges, the crosshair is drawn outside the chart as shown in the screenshot.
This commit will fix that behaviour limiting the cursor band width and position to be
always inside the chart
fix #352

fix(crosshair): limit the width of the cursor band on edges

---

.playground/playgroud.tsx
src/chart_types/xy_chart/rendering/rendering.ts
src/components/react_canvas/area_geometries.tsx
src/components/react_canvas/bar_geometries.tsx
src/components/react_canvas/line_geometries.tsx
src/components/react_canvas/reactive_chart.tsx

fix #354
This PR reapply the clippings for all the geometries but the points to avoid issues with a smaller custom domain than the one computed

fix: clip overflowing rect/lines/areas

---

src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/chart_state.ts
src/index.ts
src/specs/settings.test.tsx
src/specs/settings.tsx
stories/interactions.tsx

Add render change (`onRenderChange`) lifecycle hook to `Settings`.
`onRenderChange` is a listener to be called when chart render state changes. `isRendered` value is `true` when rendering is complete and `false` otherwise.
Required to implement visualization count for Discover and TSVB.
http://localhost:9001/?path=/story/interactions--render-change-action

feat(chart_state): add render change event

---

.playground/tsconfig.json
.storybook/tsconfig.json

This PR fixes the build issue related to `/tsx?/` files in `./.stroybook` and `./.playground` by adding these respective local directories to `tsconfig.json` `includes`.
With these changes, the files in these directories will now be enforced.

build(tsconfig): update storybook and playground tsconfig

---

src/components/react_canvas/reactive_chart.tsx

This PR fixes an issue found in SIEM where the `onBrushEnd` callback triggers a URL change and thus a rerender of the page and `Chart` components on the page. The workaround solution was to add a `500ms` `setTimeout` to allow time for the state to update before calling the `onBrushEnd` callback.
The solution as suggested by @FrankHassanabad, is to invoke the `onBrushEnd` callback following the completion of the `setState` method.
fixes #360
Notice no console errors when brushing chart and successful update of time range and chart.
Additionally, added `componentWillUnmount` method to ensure `window.removeEventListener` is called on `mouseup` event in the case where the `Chart` is unmounted before this event is called.

fix(reactive_chart): fix order of instantiation of onBruchEnd callback

---

src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/chart_state.ts
src/components/react_canvas/reactive_chart.tsx
src/specs/settings.test.tsx
src/specs/settings.tsx
stories/scales.tsx

Adds prop `hideDuplicateAxes` to settings to hide axes based on tick labels, position and title.
* Refactor axes render function.
Axis will be hidden if all of the following conditions are true:
- The first and last tick labels (with applied `tickFormat`) match
- The `length` of the ticks match
- The `titles` match, can be both `undefined`
- The `position` on the spec match
closes #368

feat(axis): option to hide duplicate axes

---

.eslintrc.js

In speaking with @nickofthyme, this is a PR to address removing the `'comma-dangle': ['error', 'always-multiline']` from eslintrc.js 
Prevents this 👇 
~~- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~~
~~- [ ] This was checked for cross-browser compatibility, [including a check against IE11]~~(https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)
~~- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials~~
~~- [ ] Unit tests were updated or added to match the most common scenarios~~

chore(.eslintrc): remove comma-dangle from eslint

---

.playground/playgroud.tsx
src/chart_types/xy_chart/rendering/rendering.bars.test.ts
src/chart_types/xy_chart/rendering/rendering.lines.test.ts
src/chart_types/xy_chart/rendering/rendering.ts
src/chart_types/xy_chart/store/utils.test.ts
src/utils/scales/scale_band.test.ts
src/utils/scales/scale_band.ts
src/utils/scales/scale_continuous.test.ts
src/utils/scales/scale_continuous.ts
src/utils/scales/scales.ts

On a previous PR: https://github.com/elastic/elastic-charts/pull/355 we fixed the clipping of
elements on the chart edges. This introduced an unwanted bug where we where removing from the chart also points that are within the chart range itself. Instead of checking if a geometry position is
within the range of the scale, this PR checks for the value to be within the domain of the scale.
fix #386
On the following examples (the same that comes with the playground) the X domain is limited to a max value of 3.8. This will remove the bar that is at position 4, the point at position 4 and limit the line to the last valid value (3).
In contrast from the current(master) version where the bar at position 4 is displayed together with a non-delimited line that goes from 3 to "somewhere"
**from:**
In …

fix(rendering): out-of-domain rendering of points/bars/lines/areas

---

.eslintignore

ESlint by default ignore folders with a name that start with a dot like .storybook and .playground.
This will un-ignore those folders allowing eslint capabilities on editor also on these folders.
see https://github.com/eslint/eslint/issues/8429#issuecomment-355967308
- ~[ ] Unit …

build(eslint): enable linting hidden folders

---

src/chart_types/xy_chart/legend/legend.test.ts
src/chart_types/xy_chart/legend/legend.ts
src/chart_types/xy_chart/rendering/rendering.test.ts
src/chart_types/xy_chart/store/__snapshots__/utils.test.ts.snap
src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/utils.test.ts
src/chart_types/xy_chart/store/utils.ts
src/chart_types/xy_chart/tooltip/tooltip.ts
src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
src/chart_types/xy_chart/utils/series.ts
src/chart_types/xy_chart/utils/specs.ts
src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
src/chart_types/xy_chart/utils/stacked_series_utils.ts
src/components/legend/legend.tsx
stories/area_chart.tsx

- Allow user to set postfix for upper and lower bound of banded series to distinguish between values sets
- Update `displayValue` type changes, fix defaulting point values from 0 to null.
Hard naming fix for #398 
closes #162

feat: banded legend values

---

src/chart_types/xy_chart/tooltip/tooltip.test.ts
src/chart_types/xy_chart/tooltip/tooltip.ts

set name to spec name then spec id
name is a global variable in ts and thus was not caught in the typecheck
closes #411

fix(tooltip): fix spec naming

---

.playground/index.html
.playground/playgroud.tsx
src/chart_types/xy_chart/domains/x_domain.ts
src/chart_types/xy_chart/rendering/rendering.ts
src/chart_types/xy_chart/store/utils.ts
src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
src/chart_types/xy_chart/utils/series.test.ts
src/chart_types/xy_chart/utils/series.ts
src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
src/chart_types/xy_chart/utils/stacked_series_utils.ts
src/components/legend/legend.tsx
src/components/react_canvas/reactive_chart.tsx
src/utils/commons.ts
stories/bar_chart.tsx

fix https://github.com/elastic/elastic-charts/issues/388
Before the fix
After the fix:

feat: fill multi-series with missing x values data points

---

src/chart_types/xy_chart/utils/scales.test.ts
src/chart_types/xy_chart/utils/scales.ts

Fixes #399 
The initial commit 4f2346e cast bandwidth in `scales.ts` in ` function computeXScale` to 0 instead of the original issue where bandwidth was being divided by 0.
Commit 209560a changed bandwidth to be `bandwidth/1` (instead of 0) which seems to be working as expected. My initial pass at this was to resolve the bug and get the x axis sizing appropriately based on the series that is visible. I plan to write or add to any unit tests but was hoping to get an initial first review to gather some feedback. Thanks!
~~- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials~~

fix: mixing bars with line or area series breaks legend toggle

---

.storybook/utils.ts
src/utils/data_generators/data_generator.ts
src/utils/data_generators/simple_noise.ts
stories/area_chart.tsx
stories/axis.tsx
stories/bar_chart.tsx
stories/styling.tsx

`seedRandom` was introduced to facilitate visual testing with consistent "random" data.
This PR abstracts the seedFunction from the `DataGenerator` class to allow a `randomNumberGenerator` function as an option in the constructor, otherwise defaults to `Math.random`.
fixes #422

fix: seedrandom dependency

---

src/components/chart_resizer.tsx

In Kibana, we start getting error messages in TSVB describing that the ResizeObserver has reached the loop limit when used together with react-beautiful-dnd library (used by EUI). This fix the issue in Kibana updating the state in the next frame instead of the current one.
fix https://github.com/elastic/kibana/issues/48589
I don't have found the root cause of that. I've found that the error disappear in Kibana in two way:
- remove all DnD component from TSVB keeping the chart
- remove the ResizeObserver from Chart, keeping EUI DnD
references: 
https://github.com/WICG/ResizeObserver/issues/38
- ~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except …

fix: resize observer loop limit exception

---

.playground/playgroud.tsx
src/chart_types/xy_chart/tooltip/tooltip.ts
src/chart_types/xy_chart/utils/axis_utils.test.ts
src/chart_types/xy_chart/utils/axis_utils.ts
src/chart_types/xy_chart/utils/specs.ts
src/utils/data/formatters.ts

to correctly handle a the tick formatting on time based series, we need to share the timeZone
parameter to the tickFormatter. When the tickFormatter is an external function, the user can
manually configure that parameter, but for the niceTimeFormatter we don't have that option already.
Instead of adding a breaking change I've added an optional parameter to the tickFormat props to
share the configured timeZone parameter
fix #427

fix(tickformatter): add timeZone to tickFormatter

---

package.json
yarn.lock

Added a [pretty-quick commit hook](https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick) otherwise the linter will balk on noncompliant code. This'll format all code `prettier`. While we may think of manually formatting a file we're editing, some refactoring steps might touch other files, or one may forget about formatting 10 concurrent files open. I don't see a downside as noncompliant formatting is currently blocking commits. 

chore: adding pretty-quick commit hook

---

src/chart_types/xy_chart/utils/series.ts

Prevent `undefined` or `null` values in `xValues`
fixes #439

fix: xDomain exclude undefined values

---

package.json
src/components/legend/legend.tsx

Prevent setting legend width when element width is `0`.
Dynamic charts such as TSBV create dynamic legend content which leaves legends squished when resize is only on initialization.
fixes #367
Adds `build:watch` script to run elastic-charts in watch mode when symlinked to kibana.
Verified in Chrome, Firefox, safari and IE. All look good, though IE seems to not be fully supported rn.

fix: legend sizing issue with no initial legend

---

src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/chart_state.ts

Taking over from:
https://github.com/elastic/elastic-charts/pull/321
Fixes in this PR:
~~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~~
~~[ ] Proper documentation or storybook story was added for features that require explanation or tutorials~~

fix(legend): disable fade of other charts when hiding an item

---

.playground/playgroud.tsx
src/chart_types/xy_chart/crosshair/crosshair_line.test.ts
src/chart_types/xy_chart/crosshair/crosshair_utils.ts
src/chart_types/xy_chart/renderer/dom/crosshair.tsx
src/chart_types/xy_chart/state/selectors/get_cursor_line.ts

This commit fix the visibility of the crosshair horizontal line, hiding
it when the pointer projected position is outside the chart area.
fix #483
- ~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)!

fix(crosshair): hide horizontal line when the pointer is outside chart

---

.playground/playgroud.tsx
src/chart_types/xy_chart/state/chart_state.interactions.test.ts
src/chart_types/xy_chart/state/chart_state.tooltip.test.ts
src/chart_types/xy_chart/state/selectors/get_specs.test.ts
src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
src/mocks/specs/specs.ts
src/specs/settings.tsx
src/utils/commons.test.ts
src/utils/commons.ts

If the tooltip type is hidden (TooltipType.None) then the tooltip should not be shown. This add the
check in the selector and includes also a smoke test for all tooltips.
*side notes*
there was already a test checking if the tooltip was visible or not, but it doesn't include a check if the highlighter was visible or not.
fix #478
- ~[ ] Proper documentation or storybook story was added …

fix(highlighter): hide it when tooltip type is None

---

.eslintrc.js
integration/jest-env-setup.ts
integration/page_objects/common.ts
package.json
src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/bar_values_utils.ts
src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/utils/rendering_props_utils.ts
src/components/chart.tsx
src/components/react_canvas/globals.ts
yarn.lock

Moving `react` and `react-dom` as peer dependency.
Upgrading `react` and `react-dom` to 16.12
Upgrading `konva` to the latest 4.x version

build(deps): move react as peer dependency, upgrade Konva

---

.playground/playgroud.tsx
src/chart_types/xy_chart/renderer/dom/highlighter.tsx

This PR fix the issue of having multiple id with the same value for the highlighter clip path. This commit add the unique `chartId` to the clipPath id.
fix #489

fix(highlighter): clip path unique id

---

.playground/playgroud.tsx
src/chart_types/xy_chart/state/chart_state.interactions.test.ts
src/chart_types/xy_chart/state/selectors/get_cursor_band.ts
src/chart_types/xy_chart/state/selectors/get_elements_at_cursor_pos.ts
src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
src/chart_types/xy_chart/state/selectors/on_pointer_move_caller.ts
src/components/chart.tsx
src/specs/settings.test.tsx
src/specs/settings.tsx
src/state/actions/events.ts
src/state/chart_state.ts
src/utils/events.ts
stories/interactions.tsx

If the consumer code doesn't take care of correctly distribute the pointer events avoiding feeding a chart with its own cursor position, it will end up with a recursive loop that ultimately throw a max stack trace. This provide the fix for such case.
**BREAKING CHANGE**: The `onCursorUpdate` Settings property is changed to a more generic
`onPointerUpdate`. The same apply for the event type `CursorEvent` that is now `PointerEvent` and can assume a `PointerOverEvent` or `PointOutEvent` shape (see TS types)
To test on previous version:
```tsx
import React from 'react';
import { Chart, Settings, TooltipType, AreaSeries, PointerEvent } from '../src';
import { KIBANA_METRICS } from '../src/utils/data_samples/test_dataset_kibana';
export class Playground extends React.Component {
chartRef: …
```

fix(external pointer): avoid recursive-loops on pointer events

---

.playground/index.html
.playground/playgroud.tsx
src/components/chart.test.tsx
src/components/chart.tsx
src/components/chart_container.tsx
src/state/selectors/is_initialized.ts
src/state/utils.ts

This commit fix the use case when no series specs are configured. Instead of throwing an error, it
will just display the "No data to display" message.

fix(specs): shows a chart message without series specified

---

.backportrc.json
CONTRIBUTING.md
package.json
yarn.lock

Add docs and config to enable backporting/patching existing version.
This uses changes directly merged to `master` to update ci to publish branches that follow the `semantic-release` [maintenance branch convention](https://github.com/semantic-release/semantic-release/blob/0785a844fa8ac1320383452ce531898be3b01f92/docs/recipes/maintenance-releases.md#publishing-maintenance-releases)

docs: add backport config and docs

---

src/chart_types/partition_chart/renderer/canvas/partition.tsx

While treemap / pie charts render in Storybook and Kibana Lens, Dashboard initially mounts the chart component with incomplete settings, so the Canvas2d context is not assigned upon mounting. The fix checks for `this.ctx` in component update, and attempts to get the proper value if still falsey. Thanks @wylieconlon for reporting and @markov00 for triaging.

fix: try to get canvas post mounting

---

package.json
src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/axis.tsx
src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/bar_values.tsx
src/chart_types/xy_chart/renderer/canvas/grid.tsx
src/chart_types/xy_chart/renderer/canvas/line_annotation.tsx
src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/rect_annotation.tsx
src/chart_types/xy_chart/specs/line_annotation.tsx
src/components/chart_container.tsx
src/components/icons/assets/dot.tsx
src/components/icons/icon.tsx
src/components/legend/legend_item.tsx
src/components/react_canvas/grid.tsx
yarn.lock

During working on https://github.com/elastic/kibana/pull/56587 I have found out that charts-related components are probably re-renders unnecessarily, so I have decided to verify that and here is the outcome from https://github.com/welldone-software/why-did-you-render
Each line in the console means unnecessary component's re-render and after the row is expanded we can see which props are equal by value but not by reference, so it causes `PureComponent` to re-render.
After my changes

fix: replace PureComponent with shouldComponentUpdate

---

package.json
src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/axis.tsx
src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/bar_values.tsx
src/chart_types/xy_chart/renderer/canvas/grid.tsx
src/chart_types/xy_chart/renderer/canvas/line_annotation.tsx
src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/rect_annotation.tsx
src/chart_types/xy_chart/specs/line_annotation.tsx
src/components/chart_container.tsx
src/components/icons/assets/dot.tsx
src/components/icons/icon.tsx
src/components/legend/legend_item.tsx
src/components/react_canvas/grid.tsx
src/utils/fast_deep_equal.ts
yarn.lock

This previous PR https://github.com/elastic/elastic-charts/pull/534 introduced the `fast_deep_equal` library to avoid multiple rendering on charts.
Unfortunately, I didn't check if IE11 compatibility of the library during the PR review.
As described here: https://github.com/epoberezkin/fast-deep-equal/issues/52 the library is not fully IE11 compatible if you just polyfill Maps/Sets. Some `for...of` loops are still there and can cause IE11 to fail if you don't transpile also the node modules.
I've copied the code + license inside the library as a first quick workaround.
We will definitely remove the function/library when fixing the double rendering internally on our reselector chain.
- ~[ ] Proper …

fix(ie11): replace fast-deep-equal with an internal copy IE11 safe

---

package.json
src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/axis.tsx
src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/bar_values.tsx
src/chart_types/xy_chart/renderer/canvas/grid.tsx
src/chart_types/xy_chart/renderer/canvas/line_annotation.tsx
src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/rect_annotation.tsx
src/chart_types/xy_chart/specs/line_annotation.tsx
src/components/chart_container.tsx
src/components/icons/assets/dot.tsx
src/components/icons/icon.tsx
src/components/legend/legend_item.tsx
src/components/react_canvas/grid.tsx
src/utils/fast_deep_equal.ts
yarn.lock

Backports the following commits to 16.1.x:
- fix(ie11): replace fast-deep-equal with an internal copy IE11 safe (#542)

fix(ie11): replace fast-deep-equal with a IE11 safe ver (#542)

---

src/chart_types/xy_chart/renderer/dom/tooltips.tsx
src/chart_types/xy_chart/state/chart_state.interactions.test.ts
src/chart_types/xy_chart/state/chart_state.specs.test.ts
src/chart_types/xy_chart/state/chart_state.timescales.test.ts
src/chart_types/xy_chart/state/chart_state.tooltip.test.ts
src/chart_types/xy_chart/state/selectors/get_annotation_tooltip_state.ts
src/chart_types/xy_chart/state/selectors/get_legend_tooltip_values.ts
src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
src/chart_types/xy_chart/state/selectors/is_tooltip_visible.ts
src/chart_types/xy_chart/tooltip/tooltip.ts
src/specs/specs_parser.tsx
src/state/actions/specs.ts
src/state/chart_state.ts

This PR is the first one to that allow us to implement a valid and clear method to sort the splitted series and allow custom rendering order of bars/area/lines in either chart, legend and tooltips.
This PR in particular clean up few small items:
- include the parsing action that that is useful to distinguish in which state we are when updating a spec. This will also ensure that the default setting component is always part of the specs array
- split the `tooltipValues` array into an header and an array with only the metric values.

chore: preparation for spec rendering order

---

src/state/spec_factory.ts

Fix issue with redux state clearing specs after consumer state update.
The redux chart state requires all specs are called every time the `Chart` component is updated. This was not happening due to the [pure](https://react-redux.js.org/api/connect#pure-boolean) option that defaults to false, basically creating a shallow equal or `memo` react component.

fix: redux connect issue related to spec upserting

---

src/state/spec_factory.ts

Backports the following commits to 16.1.x:
- fix: redux connect memo issue related to spec upserting (#563)

fix: redux connect memo issue related to spec upserting

---

.eslintrc.js
src/chart_types/partition_chart/layout/utils/calcs.ts
src/chart_types/partition_chart/layout/viewmodel/fill_text_layout.ts

Add `prefer-template` eslint rule to the eslint to suggest using template literals instead of string concatenation.
https://eslint.org/docs/rules/prefer-template

build: add prefer-template eslint rule

---

NOTICE.txt

This commit fix a small typo on the NOTICE.txt file

chore: fix notice library name typo

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

A small cleanup on the github templates

docs: clean github templates

---

src/chart_types/xy_chart/specs/line_annotation.test.tsx
src/chart_types/xy_chart/specs/line_annotation.tsx

The `LineAnnotation` component doesn't use the `specComponentFactory` because it render the marker
if available. We have to always keep the spec updating the state on every lifecycle thus removing
the deepEqual check on the shouldComponentUpdate did the trick.
fix #604

fix(line_annotation): keep the spec in state after chart rerender

---

.playground/index.html
.playground/playground.tsx
src/chart_types/partition_chart/layout/viewmodel/viewmodel.ts
src/chart_types/partition_chart/state/selectors/picked_shapes.test.ts
src/chart_types/partition_chart/state/selectors/picked_shapes.ts
src/mocks/specs/specs.ts
stories/interactions/4_sunburst_slice_clicks.tsx

This commit aligns the shape of the passed parameter of the onElementClick listener to the one passed by a sunburst. For each single hovered shape (usually only one shape at a time) it returns the values for each layer of the treemap
fix #624

fix(treemap): align onElementClick parameters to sunburst

---

src/chart_types/xy_chart/tooltip/tooltip.test.ts
src/chart_types/xy_chart/tooltip/tooltip.ts

Mark value was being called with the axis `tickFormat` function with null values. I don't think the mark value would ever be called with an axis formatted so I removed that and just pass the mark value.

fix: tickFormat called on mark value

---

.playground/playground.tsx
src/chart_types/goal_chart/renderer/canvas/connected_component.tsx
src/chart_types/goal_chart/state/chart_state.tsx
src/chart_types/partition_chart/renderer/canvas/partition.tsx
src/chart_types/partition_chart/renderer/dom/highlighter_hover.tsx
src/chart_types/partition_chart/renderer/dom/highlighter_legend.tsx
src/chart_types/partition_chart/state/chart_state.tsx
src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
src/chart_types/xy_chart/renderer/dom/annotation_tooltips.tsx
src/chart_types/xy_chart/renderer/dom/brush.tsx
src/chart_types/xy_chart/renderer/dom/crosshair.tsx
src/chart_types/xy_chart/renderer/dom/highlighter.tsx
src/chart_types/xy_chart/state/chart_state.tsx
src/components/chart.tsx
src/components/chart_container.tsx
src/components/legend/legend.tsx
src/components/tooltip/tooltip_portal.tsx
src/state/chart_state.ts
src/state/selectors/get_internal_is_intialized.ts

This fix the error thrown when a chart is rendered without a series spec, usually caused how the consumer renders the chart components.
See the playground example and the comment here: https://github.com/elastic/kibana/pull/64759#issuecomment-621996613

fix: empty charts causing errors

---

src/mocks/utils.ts
src/utils/data_generators/data_generator.ts
src/utils/data_generators/simple_noise.ts
tsconfig.lib.json

Bug caused by `DataGenerator` Class now expecting a random number generator. Broke EUI docs.
- Move around types to exclude mocks directory
- Remove import of seedrandom from dist files
- Add default rng function for DataGenerator
> We should move `pallettes.ts` out of `mocks/` all prevent any src code in this directory, might be best to move it to the root folder or in a testing utils root directory.

fix: build/type issue with DataGenerator

---

lint-staged.config.js
package.json
yarn.lock

This PR updates the `commit-msg` hook to only lint staged files on commit.
Before we called `yarn lint` which defines all files to be linted in the project regardless.

ci: lint only staged files

---

.storybook/style.scss
integration/page_objects/common.ts
src/components/_global.scss
src/components/portal/_portal.scss
src/components/portal/tooltip_portal.tsx

Fix the scrollbar appearance when showing a tooltip on Lens/Kibana.
This was caused by the `invisible` class and its child taking space on the bottom of the page before popperjs can position the tooltip on the page

fix: apply positioning to hidden tooltip

---

package.json

Fix `yarn kbn bootstrap` in kibana. Adding them to `devDependencies` created an error with yarn. Moving these to `optionalDependencies` is a temporary solution until the we switch to yarn workspaces.
The error is posted below.
```node
> yarn kbn bootstrap
yarn run v1.21.1
$ node scripts/kbn bootstrap
info [kibana] running yarn
$ node ./preinstall_check
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "typescript@3.9.5" is incompatible with requested version "typescript@~3.7.2"
success Already up-to-date.
succ 13 bootsrap builds are cached
info [@kbn/ui-shared-deps] running [kbn:bootstrap] script
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /usr/local/Cellar/yarn/1.21.1/libexec/bin/yarn.js run kbn:bootstrap
error Command …
```

fix: move redux dev deps to optional

---

.ci/jobs/elastic+elastic-charts+pr-vrts-2.yml
.ci/jobs/elastic+elastic-charts+pr-vrts.yml
.ci/jobs/elastic+elastic-charts+pull-request.yml
.ci/vrts.sh

Split VRTs in two parts: one for the `all.test.ts` and another for all the others

ci: split VRTs in two parts

---

src/chart_types/xy_chart/state/chart_state.specs.test.ts
src/state/chart_state.ts

This commit reset the chart state to not initialized when removing a spec. After #723 PR that
reduced the number of steps on the state machine when parsing, the removeSpec action wasn't
accounted on that refactoring causing side effects when removing/switching a spec on the chart
configuration due to the state being in an wrong status.
fix #738

fix: set uninitialized state when removeSpec action is called

---

yarn.lock

Upgrade dependencies with security vulnerabilities.
- [`minimist`](https://github.com/elastic/elastic-charts/network/alert/yarn.lock/minimist/open)
- [`kind-of`](https://github.com/elastic/elastic-charts/network/alert/yarn.lock/kind-of/open)

fix: update dep vulnerabilities, minimist and kind-of

---

.github/workflows/smoke_tests.yaml

Fix `browser-ie` pr check
fix per https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

ci: fix browser-ie failure

---

.eslintrc.js
src/chart_types/xy_chart/domains/y_domain.ts
src/components/chart.tsx
src/components/error_boundary/error_boundary.tsx
src/components/error_boundary/errors.ts
src/components/error_boundary/index.tsx

fix #776
Allow gracefully handling/catching of errors at a top level.
Now calling errors as `GracefulError` will still show in the console but return an empty chart, not a blank element.
```ts
throw new GracefulError('Something went wrong');
```

fix: allow graceful error handling

---

package.json
src/components/chart.tsx
yarn.lock

Resolve dependency issue with `@elastic/charts@21.1.1`
```
WARNING in /Users/nicholaspartridge/Documents/repos/kibana/node_modules/@elastic/charts/dist/components/chart.js
Module not found: Error: Can't resolve 'redux-immutable-state-invariant' in '/Users/nicholaspartridge/Documents/repos/kibana/node_modules/@elastic/charts/dist/components'
WARNING in /Users/nicholaspartridge/Documents/repos/kibana/node_modules/@elastic/charts/dist/components/chart.js
Module not found: Error: Can't resolve 'redux-logger' in '/Users/nicholaspartridge/Documents/repos/kibana/node_modules/@elastic/charts/dist/components'
```

fix: remove unused redux dev middlewares

---

src/chart_types/xy_chart/state/selectors/compute_series_domains.ts
src/chart_types/xy_chart/state/utils/utils.ts
src/chart_types/xy_chart/utils/series.ts

Allows a blind sorting option on `Settings` called `enableVislibSeriesSort` to loop through all `yAccessors` then all the data.
This option is bind as in not added to the `SettingSpec` to avoid usage, outside of vislib, until #795 allows a sorting alternative.
> Notice the change in the order of the y accessors between the options.
```tsx
import React from 'react';
import { Chart, Settings, Position, Axis, BarSeries, ScaleType } from '../src';
const data = [
// Flight Delay Minutes |	Cancelled: Descending |	OriginAirportID: Descending	Count |	Max AvgTicketPrice
{ x: 0, g1: 'false', g2: 'USA', y1: 2, y2: 847.323974609375 },
{ x: 0, g1: 'true', g2: 'Canada', y1: 1, y2: 652.268005371094 },
{ x: 30, g1: 'false', g2: 'Canada', y1: 5, y2: 1127.20959472656 },
{ x: 30, g1: 'true', g2: 'USA', y1: …
```

feat: blind sorting option for vislib

---

.playground/playground.tsx
api/charts.api.md
src/chart_types/heatmap/layout/config/config.ts
src/chart_types/heatmap/layout/types/config_types.ts
src/chart_types/heatmap/specs/heatmap.ts
src/chart_types/heatmap/state/selectors/tooltip.ts
src/index.ts
src/specs/settings.tsx

- Add configurable names for X and Y axes labels 
- Add extra values to the tooltip info for X and Y axes, fix `formattedValue` for the cell value
- Export `HeatmapConfig` as `RecursivePartial`

feat: heatmap tooltip enhancements and fixes

---

integration/page_objects/common.ts
src/chart_types/xy_chart/state/chart_state.interactions.test.ts
src/state/reducers/interactions.ts
src/utils/point.ts

This fix reduces the situation where a drag event is fired instead of a click one.
The fix adds the following thresholds:
- a 100ms threshold before the mouse-down time and the current time to consider the movement for dragging purposes
- a 4-pixel delta between mouse-down and the current position  to consider the movement for dragging purposes
fix #748

fix(interactions): recognise drag after 100ms and 4px

---

src/chart_types/heatmap/layout/viewmodel/viewmodel.ts

Resolve the max number of ticks based on the formatted label and the chart width. 
A proper fix will require `ScaleContinuous` to take into account this value as a limit during creating nice rounded tick values.

fix(heatmap): x-axis labels overlapping for time series data

---

src/chart_types/xy_chart/state/chart_state.interactions.test.ts
src/state/reducers/interactions.ts

This fix changes the drag detection checking only the delta change between the mouse down position and the current mouse move removing the time check. This allows fast interaction used in CI functional tests without the need to add a delay between actions.

fix: detect dragging only by the delta changes

---

.github/workflows/auto_release.yaml

With the idea of dismiss Travis CI for release, I'm adding a new gh workflow that can be manually triggered and do both release and gh pages deploy.
I'm using this https://github.com/marketplace/actions/github-pages-action for deploy.
Few security tokens need to be added for `semantic-release` before merging on master

ci(release): use gh workflow to manually release and push

---

api/charts.api.md
src/chart_types/heatmap/layout/config/config.ts
src/chart_types/heatmap/layout/types/config_types.ts
src/chart_types/heatmap/state/selectors/get_x_axis_right_overflow.ts

This feature allows a fixed width for the right margin of the heatmap.
This allows aligning multiple vertical heatmaps on top of each other.

feat(heatmap): allow fixed x right margin

---

src/components/legend/_legend_item.scss

Fixes #710 Text from the legend can be selected and copied.

feat(legend): allow legend text to be copyable

---

stories/mixed/6_fitting_stacked.tsx

Add randomness toggle on fit stacked series story per chat with @wylieconlon. Should be disabled by default to easily see the difference.

docs: add randomness toggle on fit stacked series story

---

src/chart_types/xy_chart/rendering/utils.ts
src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.test.ts

This PR fixes a regression on the point highlighter for line and area charts.
Due to recent changes on the data processing pipeline, the geometry canvas coordinates are composed by a chart relative x,y position + a transpose function.
The inverse function that checks if the mouse if over the geometry was not updated to reflect this change.
A functional test is also added and tested against the previous code.

fix: point highlight based on geom position and transform

---

src/chart_types/xy_chart/state/selectors/get_debug_state.ts

When using the new `debugState`, the axis labels where using the non-filtered ticks when using either `showOverlappingLabels` or `showOverlappingTicks` options. This PR uses only the visible ticks and filters out empty string labels.

fix: empty labels on debug state

---

src/components/__snapshots__/chart.test.tsx.snap
src/components/chart.test.tsx
src/components/legend/__snapshots__/legend.test.tsx.snap
src/components/legend/legend.test.tsx

Make snapshots multiline to improve diffing and readability.

chore: convert single line snapshots to multiline

---

src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts

Backports the following commits to 24.4.x:
- fix: external tooltip legend extra value sync (#993)

fix: external tooltip legend extra value sync (#993) [24.4.x]

---

api/charts.api.md
src/components/portal/tooltip_portal.tsx
src/components/portal/types.ts
src/index.ts
stories/bar/55_tooltip_boundary.tsx

closes #1062 
Adds an artificial [`padding`](https://popper.js.org/docs/v2/utils/detect-overflow/#padding) around the specified `boundary` element to contain tooltip within boundaries with top margins.
https://user-images.githubusercontent.com/19007109/110491875-49c5c380-80b7-11eb-8949-31e3ee33131a.mp4
> **Note:** This does _not_ impact the tooltip offset for the achor.

fix(tooltip): add boundary padding

---

api/charts.api.md
src/components/portal/tooltip_portal.tsx
src/components/portal/types.ts
src/index.ts
stories/bar/55_tooltip_boundary.tsx

Backports the following commits to 25.0.x:
- fix(tooltip): add boundary padding (#1065)

fix(tooltip): add boundary padding (#1065) [25.0.x]

---

src/chart_types/xy_chart/state/selectors/get_brush_area.test.ts
src/chart_types/xy_chart/state/selectors/get_brush_area.ts
src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
src/mocks/specs/specs.ts
stories/interactions/9a_brush_selection_linear.tsx
stories/small_multiples/1_grid.tsx
stories/small_multiples/2_vertical_areas.tsx
stories/small_multiples/3_grid_lines.tsx

This PR forced the brush tool to work per panel when using small multiples. This behavior is built to works independently from the presence or absence of a small multiples configuration.
It works by forcing the brushable area to be constraint between the boundaries of the panel where the brushing event started. The brush selection doesn't move between panels and the coordinate of the mouse down event determines the limiting panel.
I've cleaned up the code to compute the brush area and also updated the unit test by mocking the SmallMultiple specs
fixes #1070
https://user-images.githubusercontent.com/1421091/110787477-a66adf00-826d-11eb-9f4e-15f0b89c857a.mp4

fix(brush): force brush tool per panel

---

src/chart_types/xy_chart/state/selectors/get_brush_area.test.ts
src/chart_types/xy_chart/state/selectors/get_brush_area.ts
src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
src/mocks/specs/specs.ts
src/utils/common.ts
stories/interactions/9a_brush_selection_linear.tsx
stories/small_multiples/1_grid.tsx
stories/small_multiples/2_vertical_areas.tsx
stories/small_multiples/3_grid_lines.tsx

Backports the following commits to 25.0.x:
- fix(brush): force brush tool per panel (#1071)

fix(brush): force brush tool per panel (#1071) [25.0.x]

---

src/components/portal/tooltip_portal.tsx

Adds `offset` back to `flip` modifier regardless of `padding`.

chore: always use offset with flip modifier

---

api/charts.api.md
src/chart_types/wordcloud/layout/types/viewmodel_types.ts
src/chart_types/wordcloud/layout/viewmodel/viewmodel.ts
src/chart_types/wordcloud/renderer/svg/connected_component.tsx
src/chart_types/wordcloud/specs/index.ts
src/chart_types/wordcloud/state/chart_state.tsx
stories/wordcloud/1_wordcloud.tsx

chore(wordcloud): improvements

---

.prettierrc.json
api-extractor.json

By default, `api-extractor` uses `CRLF` as line-ending configuration.
Since our code uses `LF`, as specified in the `.editorconf` file, it's better to align to that configuration for every file.
I'm using a configuration introduced here: https://github.com/microsoft/rushstack/pull/1626
I've noticed multiple situations where the generated export is interpreted in github/diff viewer as completely new due to this different line endings configuration. I hope with that to avoid completely this issue in the future

chore: use LF as new line configuration on API-extractor

---

api/charts.api.md
src/chart_types/goal_chart/state/selectors/picked_shapes.ts
src/chart_types/partition_chart/layout/types/viewmodel_types.ts
src/chart_types/partition_chart/layout/viewmodel/picked_shapes.ts
src/chart_types/partition_chart/layout/viewmodel/viewmodel.ts
src/chart_types/partition_chart/renderer/canvas/partition.tsx
src/chart_types/partition_chart/state/selectors/geometries.ts
src/chart_types/partition_chart/state/selectors/picked_shapes.test.ts
src/chart_types/partition_chart/state/selectors/tree.ts
src/chart_types/wordcloud/state/selectors/picked_shapes.ts
src/specs/group_by.ts
src/specs/settings.tsx
stories/interactions/4_sunburst_slice_clicks.tsx
stories/small_multiples/7_sunbursts.tsx

Small multipies events now pass on smAccessorValue, which is the unformatted value returned by the `by` function in `<GroupBy>`.
See the `Actions` tab in http://localhost:9001/?path=/story/small-multiples-alpha--sunbursts and hover or click on slices.

feat(partitions): small multipies events pass on smAccessorValue

---

stories/mosaic/10_mosaic_simple.tsx

Comparison radio buttons in the mosaic story that got added by https://github.com/elastic/elastic-charts/pull/1113

test(partition): mosaic plot story knob for alternatives selector

---

global.d.ts
integration/tsconfig.json
playground/tsconfig.json
storybook/tsconfig.json
tsconfig.json

Fix issue with custom jest matchers and global types not registering in vscode.

build: fix types in vscode tsconfigs

---

packages/charts/src/chart_types/xy_chart/axes/axes_sizes.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/lines.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/axes/global_title.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/axes/index.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/axes/line.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/axes/tick.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/panels/global_title.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/panels/panel_title.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/panels/panels.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/line.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
packages/charts/src/chart_types/xy_chart/rendering/rendering.test.ts
packages/charts/src/chart_types/xy_chart/state/chart_state.test.ts
packages/charts/src/chart_types/xy_chart/state/selectors/compute_axis_ticks_dimensions.ts
packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
packages/charts/src/chart_types/xy_chart/state/selectors/merge_y_custom_domains.ts
packages/charts/src/chart_types/xy_chart/state/utils/utils.test.ts
packages/charts/src/chart_types/xy_chart/utils/axis_utils.test.ts
packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
packages/charts/src/chart_types/xy_chart/utils/dimensions.test.ts
packages/charts/src/chart_types/xy_chart/utils/dimensions.ts

Logic preserving refactoring in preparation for added time axis functionality. No change to the API or test results.

refactor(xy): prepare for time axis improvements

---

packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
packages/charts/src/chart_types/heatmap/state/selectors/get_brushed_highlighted_shapes.test.ts
packages/charts/src/chart_types/heatmap/state/selectors/get_picked_cells.ts

The heatmap brush selection, on temporal heatmaps, has been fixed correctly computing the visible area and limiting the area to the only hovered cells.
A recent merged change #1212 caused this issue. The brush area was computed without considering the right end value for time series.
The PR adds also two more unit test to cover the case
fix #1229

fix(heatmap): pick correct brush end value

---

.releaserc.js

The current spread operator wrongly spread the `semantic-release-slack-bot` plugin definition as there were two different plugin.
This PR correct that spread, keeping the plugin name and the configuration within an array as requested

ci: fix semantic-release slack-bot config

---

yarn.lock

upgrade `caniuse-lite`
Correct console warning...
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```

chore: upgrade caniuse-lite dep

---

.releaserc.js
packages/charts/package.json

Fix package versioning script
The path to the `pkgRoot` in the `@semantic-release/npm` config should be a full resolved path as shown below.
https://github.com/semantic-release/npm/blob/d5cab62ee88e38f2b866feda5c7af8fce95c0173/lib/prepare.js#L5-L6

ci: fix package versioning script

---

packages/charts/src/chart_types/goal_chart/renderer/canvas/canvas_renderers.ts
packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
packages/charts/src/chart_types/partition_chart/renderer/canvas/partition.tsx
packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
packages/charts/src/components/brush/brush.tsx
packages/charts/src/renderers/canvas/index.ts

Removes the `ctx.clearRect(-200000, -200000, 400000, 400000)` present in a couple of chart types. Also, more places use the common, `clearCanvas` method that got updated for transform independence 
Also, removed one or two unnecessary `withContext` and lightly restructured some surrounding code 
The global canvas erasure (in `master` and in this branch too) is currently possible, because the canvas isn't shared: each chart type possesses it, so it's safe to clear everything. In the future, we do need to refine this, for example, if
- we want heterogeneous small multiples or tiling layouts
- we want to update just one panel, while leaving the rest untouched (eg. for perf reasons, no need to recalc/rerender)
Follow-up on #1286 which also eliminated some large canvas dimension operations

chore(xy): avoid large dimensions in ctx.clearRect

---

packages/charts/src/chart_types/goal_chart/renderer/canvas/canvas_renderers.ts
packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
packages/charts/src/chart_types/partition_chart/renderer/canvas/canvas_renderers.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/areas.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/bars.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/bubbles.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/grids.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/lines.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/panels/panels.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/arc.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/line.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/path.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/shapes.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/utils/debug.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/utils/panel_transform.ts
packages/charts/src/components/brush/brush.tsx
packages/charts/src/renderers/canvas/index.ts

Callbacks for `withContext` and, occasionally, other such wrappers to use the outer ctx, as we don't juggle them anyway. The main motivation is to avoid the awkwardness of avoidance of shadowing, while keeping the somewhat sensible rule against shadowing. Stemming from this [ask](https://github.com/elastic/elastic-charts/pull/1307#discussion_r691952011) by @markov00

refactor: reduction of canvas context threading

---

.ci/global_setup.sh
.github/workflows/api_extractor_check.yaml
.github/workflows/auto_release.yaml
.github/workflows/ci.yaml
.github/workflows/deploy_docs.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml
.github/workflows/unit_test.yaml

Disabling the Puppeteer Download when installing the npm dependencies, following the advice here: https://github.com/gidztech/jest-puppeteer-docker
Could save few seconds on CI :)

ci: disable local puppeteer download 

---

package.json

After migrating to `Elastic License 2.0` we forgot to upgrade the package.json license header to the right one.
cc @ghudgins 
ref: https://github.com/elastic/kibana/issues/105614

fix(build): fix license in package.json

---

package.json
playground/playground.tsx
playground/webpack.config.js

Fix playground build after breaking it in #1231 or #1178 
script now functions as intended...
```
yarn playground
```

docs(playground): fix webpack config

---

packages/charts/api/charts.api.md
packages/charts/src/state/selectors/get_chart_theme.ts
packages/charts/src/utils/common.test.ts
packages/charts/src/utils/common.ts
packages/charts/src/utils/themes/merge_utils.ts

Fix theming override logic to allow initial partial value as empty object (`{}`). 
Before something like the chart below would ignore the `dash` definition because the first partial is empty.
```tsx
export const Example = () => {
return (
<Chart>
<Settings
baseTheme={useBaseTheme()}
theme={[
{},
{
crosshair: {
line: {
dash: [4, 4],
},
},
},
EUI_CHARTS_THEME_LIGHT.theme,
]}
/>
</Chart>
);
};
```
Now the dash is correctly shown.
The `mergePartial` logic had two issues...
1. The merge optional values logic only ran if the first partial was not `undefined`. Now it checks for any keys on all partial values at the given level and applies mutations to the `baseClone` as needed, if either the `partial` has applicable keys or any `additionalPartials` have applicable keys.
2. The final mapping over …

fix(theme): merge partial with empty initial partial

---

.releaserc.js

The current `semantic-release` configuration creates a comment on each PR that is released. There is a [bug](https://github.com/semantic-release/github/issues/359) that cause re-commenting on the same PR over and over again if the commit message has the `fix #123`  caption like in https://github.com/elastic/elastic-charts/issues/1108#issuecomment-854838687
This creates a lot of noises in the github notifications.

build: disable commenting on successfully release PRs

---

packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts

The pointer cursor will not be used in over element actions to avoid misleading users.
Closes #1437

fix(xy): remove pointer cursor for onElementOver

---

packages/charts/src/components/accessibility/partitions_data_table.tsx
storybook/stories/interactions/16_cursor_update_action.story.tsx
storybook/stories/interactions/17_png_export.story.tsx
storybook/stories/interactions/18_null_values.story.tsx

fix createRef with useRef in Functional Components.

fix: replace createRef with useRef in Functional Components.

---

packages/charts/api/charts.api.md
packages/charts/src/chart_types/partition_chart/layout/types/config.ts
packages/charts/src/index.ts

This PR adds back the `PartitionConfig` types as deprecated to avoid breaking type changes in eui versioning. See https://github.com/elastic/eui/pull/5492

fix: export deprecated partition config types

---

packages/charts/src/chart_types/partition_chart/layout/types/config_types.ts
packages/charts/src/chart_types/partition_chart/layout/types/viewmodel_types.ts
packages/charts/src/chart_types/partition_chart/layout/viewmodel/viewmodel.ts
packages/charts/src/chart_types/partition_chart/specs/index.ts
packages/charts/src/mocks/specs/specs.ts

Restored tweening (animation) to flamegraph that stopped working at 6db267718cbc37c678c565ac4a0a174cc3e9df9f 
The work that moved numerous config options into the theme turned the previously mandatory `animation` property optional. This watered up preexisting TS type checks, as optionals often do, and we don't yet have mid-flight VRT for (currently alpha) animations, so it flew under the radar.
The fix restores the mandatory nature of `animation` and supplies a default zero `duration` for it.
In the future it might become part of the theme, would need a convo.
Closes https://github.com/elastic/elastic-charts/issues/1540

fix(flamegraph): solve animation regression

---

packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts

The current tick count estimation is based on a sample label created with `Date.now()`.
This can cause unpredictable tick count, in particular when running VRTs on the CI server.
The change uses the domain min value.
This will fix the VRTs flakyness related to 
`integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-3-1.png`

fix(heatmap): fix unpredictable tick count

---

integration/tests/timezone.test.ts
packages/charts/src/chart_types/xy_chart/domains/x_domain.test.ts
packages/charts/src/chart_types/xy_chart/domains/x_domain.ts
packages/charts/src/chart_types/xy_chart/state/utils/utils.test.ts
packages/charts/src/chart_types/xy_chart/utils/axis_utils.test.ts
packages/charts/src/chart_types/xy_chart/utils/specs.ts
packages/charts/src/mocks/xy/domains.ts
packages/charts/src/scales/scale_continuous.ts

Backports the following commits to 40.x:
- fix(xy): switch default timezone to `local` (#1544)

feat(xy): switch default timezone to `local` (#1544) [40.x]

---

packages/charts/package.json
packages/charts/src/components/chart_resizer.tsx

The [Resize Observer API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) is available in all major browsers and we don't need to polyfill it anymore.
@nickofthyme I've also updated the ech version in the storybook package. I know that it's not used directly, but this can prevent downloading unnecessary libraries if we keep them in sync. Do you know a better way to link a workspace as a dependency without using the specific package version?

fix(deps): remove the ResizeObserver polyfill

---

packages/charts/src/components/chart_resizer.tsx

JSDOM doesn't have the `ResizeObserver` available in the `global` object but instead is available directly from the `window` object.
Solves Kibana jest test failures [here](https://buildkite.com/elastic/kibana-pull-request/builds/19241)

fix: use window scope to call the ResizeObserver

---

packages/charts/package.json
packages/charts/src/components/chart_resizer.tsx

The PR https://github.com/elastic/elastic-charts/pull/1569 doesn't fix completely the issue with the missing `resize-observer-polyfill`. Before digging deeper into the root cause I will revert the changes applied in 542f2bf3a20d5463c14d614cb55491430763e133

revert: remove of resize observer polyfill

---

packages/charts/src/chart_types/heatmap/state/selectors/get_debug_state.ts

After the changes in https://github.com/elastic/elastic-charts/pull/1514 the debug state returns every labels.
It should instead return only the visualized ones

fix(heatmap): align debug state with the visualized axis labels

---

packages/charts/src/_eui_imports.scss

This fix reverts [a suggestion](https://github.com/elastic/elastic-charts/pull/1463#discussion_r747686611) that imported unwanted classes into our exported CSS files. 
We are now importing only mixins and variables that will not pollute the generated CSS with unwanted classes like the date picker and some utility classes

fix(style): don't export EUI styles

---

packages/charts/src/chart_types/xy_chart/annotations/rect/dimensions.ts
packages/charts/src/chart_types/xy_chart/annotations/rect/types.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/animations/README.md
packages/charts/src/chart_types/xy_chart/renderer/canvas/animations/index.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/lines.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/rect.ts
packages/charts/src/mocks/annotations/annotations.ts

Fix bug with animations logic flashing from `0` values to target values with multiple annotation specs.
https://user-images.githubusercontent.com/19007109/166853537-dbbb9dcc-ca98-425c-ac19-84f92ca97067.mp4
Notice:
- The flashing when both annotations are blurred as the value transitions, it does not know the current value and defaults to `0` as a fallback, hence the flashing.
- The instant tweening when hovering the annotations then hovering over a bar/geom.
https://user-images.githubusercontent.com/19007109/166853348-277f93b3-ac49-43d8-8742-20caaeb08bc5.mp4
Both issues are no longer present
The issue was caused by using conditional or parameterized keys. The animations logic work by tracking new values for each animated value.  If you have an animation key that is conditional, say …

fix(animations): initialize all conditionalized props

---

packages/charts/src/chart_types/flame_chart/flame_chart.tsx
packages/charts/src/chart_types/flame_chart/render/draw_canvas.ts
packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
packages/charts/src/chart_types/flame_chart/shaders.ts
packages/charts/src/common/default_theme_attributes.ts
packages/charts/src/common/kingly.ts
packages/charts/src/state/selectors/get_legend_size.ts

This PR adds context loss handling to the WebGL flame chart. 
Web standards do not guarantee that rendering resources aren't lost. Rendering resources can be lost for various reasons, such as an overloaded system (even due to other applications), graphics driver error, or too many contexts. In fact, a context loss may even happen with Canvas2d. But it's more important for WebGL, where a context can be lost even simply having too many distinct WebGL canvases on a page (more than 16).
The PR contains other minor refactoring, such as pulling the font type from the default font, and updating `kingly.ts` to the version that can run more WebGL charts that are in the pipeline. For example, via configurable polygon vertex winding order.

feat(flame): context loss handling

---

packages/charts/src/chart_types/flame_chart/flame_chart.tsx
packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
packages/charts/src/chart_types/flame_chart/render/draw_canvas.ts
packages/charts/src/chart_types/flame_chart/render/draw_webgl.ts
packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
packages/charts/src/chart_types/flame_chart/render/upload_to_webgl.ts
packages/charts/src/chart_types/flame_chart/shaders.ts
packages/charts/src/chart_types/flame_chart/types.ts
packages/charts/src/common/kingly.ts

Switch from the conceptually simpler, less efficient (and removed by WebGPU) individual uniforms to the more verbose buffered uniform blocks (UBO) introduced with WebGL2.
The vertex shaders for visible rendering vs. the simpler, geom picking rendering (no gaps, no corner radius) have been split, but the common parts got abstracted out.
Avoidance of a loop with arbitrary branching and discard in favor of a single math expression with a single discard
Removal of the custom templated string functions as they didn't add a lot of value
Moving the context loss/regain event handlers into their own methods
Tighter typing for the keys of the column representation (vertex attribute names)
Reversal of a former shader change which resulted in a too light hover effect
Inclusion of the canvas offsets …

performance(flame): uniform buffers and shader rework

---

packages/charts/src/chart_types/flame_chart/flame_chart.tsx
packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
packages/charts/src/chart_types/flame_chart/render/draw_webgl.ts
packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
packages/charts/src/chart_types/flame_chart/shaders.ts

As the chart zooms and pans, it's useful to briefly pulsate the activated node.
It's a short pulsation for click focus, because
- the user knows where he/she clicked, it's a direct interaction
- the node will already be present in the current visible area
It's a long pulsation for the search hit focus, because
- the user doesn't know where it'll arrive
- there is no visual indicator for what the actual hit is
- esp. with the current, suboptimal pan (no zoom out/in) it takes time for the hit to arrive into the visible area
A more permanent, additional marker (eg. magenta border around the node, which stays until the next interaction not including hovering) is planned for a separate PR. It's a former item titled _Cycling through matches should have a more salient style on the actively …

feat(flame): pulsate node on click focus and search hit focus

---

packages/charts/src/chart_types/flame_chart/flame_chart.tsx
packages/charts/src/chart_types/flame_chart/shaders.ts
packages/charts/src/common/kingly.ts
storybook/stories/icicle/04_cpu_profile_gl_flame.story.tsx

Fixes:
- the Safari Metal shader compiler has a bug (causing no render at all) that needed a 1-liner workaround, see the [1st commit](https://github.com/elastic/elastic-charts/pull/1695/commits/599db56f4cd240aa43e8bdd1c81127ab97f340e5).
- click focusing with certain browser zoom levels (eg. 110% in Chrome) and pinch zoom stopped working, due to a regression introduced with these [lines](https://github.com/elastic/elastic-charts/pull/1682/files#diff-f017ed451ccf2474f26b0e480ee6ade71500e04765029c93afd6925249d205bfR365-R371) - thanks @ghudgins for the report
The PR also contains 
- visual improvements to the blinking focus indicator: 
- when clicking on a node, or advancing to another text search hit, the pulsation makes full periods, so the end of the pulsation is smooth
- the pulsation …

fix(flame): cross browser issues

---

packages/charts/src/chart_types/flame_chart/flame_chart.tsx

When using the search field, or even after a manual pan drag on the chart, the following keyboard shortcuts work:
- Enter: next hit
- Shift Enter: previous hit
- Escape: clear search field
Partial fulfilment of keyboard accessibility in https://github.com/elastic/elastic-charts/issues/1671

feat(flame): keyboard shortcuts for the text field

---

packages/charts/src/chart_types/flame_chart/flame_chart.tsx
storybook/stories/wordcloud/1_wordcloud.story.tsx

Removes the keyboard focus border that interferes with the zoom/pan focus indicators on the top and left. A future PR needs to address chart focusability including adding the missing keyboard interactions for navigation. Also contains a wordcloud story fix ht Marco
In current `master`, the issue is reproducible best in Chrome, when clicking on the large chart, then hitting the Escape or some other key. A keyboard focus line on top and left appear, coniciding with the rendered zoom/pan focus lines

fix(flame): no focus border

---

packages/charts/src/chart_types/xy_chart/axes/timeslip/multilayer_ticks.ts
storybook/stories/area/21_with_time_timeslip.story.tsx

When resizing too much a time series chart with a multilayer time axis, the function that computes the ticks can receive a a zero-length array of `layers`.  Typescript probably doesn't pick up correctly a mis-typed reduce and it propagated through without getting noticed causing an un-recoverable error as reported in the [linked issue](#https://github.com/elastic/elastic-charts/issues/1592) and the Kibana one.
This PR fixes it by adding the correct return type to the function and fixing the reduce function initialization.
The timeslip story is also updated with a switch to show the legend simplifying the reproducibility of the issue.
fix #1592

fix: return always a full projection in multilayerAxisEntry

---

packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_dimensions.ts
packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
storybook/stories/heatmap/5_theming.story.tsx

This PR fixes a small bug related to the way we compute the max width size of the vertical axis.
See the deployed story `Heatmap -> Theming` and check the two added theaming knobs: `yAxisLabel width type` and `yAxisLabel width max/static`
The current configuration in the theme `yAxisLabel:{width:{max: number}}` wasn't working correctly

fix(heatmap): correctly compute vertical axis width max size

---

packages/charts/src/chart_types/xy_chart/state/selectors/on_projection_area_caller.ts
packages/charts/src/components/chart_container.tsx
packages/charts/src/components/chart_status.tsx

Working at #1729 leads to an interesting issue regarding the asynchronous callback.
In particular, we were calling the `onChartRendered` and `onProjectionAreaChanged` callbacks in a new macro task thanks to a `requestAnimationFrame`.
The reasons to avoid this way of handling callbacks are:
- give the freedom to the user to choose how they want to execute/queue the task in their own environment
- events caused by mouse events are already async by nature
- those callbacks should be used only for small side effects, like triggering a focus, a slight change in the state (like disabling a loading spinner) etc the user should not attach long-running sync methods to these events.
This PR removes the use of RAF in favor of sync calls.
This solves a side issue in the composable story where the …

fix(events): remove async callbacks from code

---

.buildkite/utils/pipeline/steps.ts
e2e/playwright.config.ts

Move all buildkite jobs to `datavis-n2-2` agent `queue`.

ci: move buildkite to new datavis agent queue

---

.buildkite/scripts/steps/eslint.ts
.buildkite/steps/api_check.ts
.buildkite/steps/eslint.ts
.buildkite/steps/jest.ts
.buildkite/steps/type_check.ts
.buildkite/utils/github.ts

When `dependabot` and others, update a PR it could update only the `yarn.lock` and not the touch the `package.json`. This fix triggers the step checks correctly in such a case. Also the `minimatch` options ignore dot paths (i.e. `.buildkite/`) by default, this now respects changes to dot paths by default.

ci: fix skip logic for dependabot

---

.buildkite/utils/exec.ts
e2e/page_objects/common.ts
e2e/playwright.config.ts
e2e/tests/annotations_stories.test.ts

Adds `maxDiffPixelRatio`, `maxDiffPixels` and `threshold` options to screenshot options and passes to playwright `expect(element).toMatchSnapshot()` method.
Fixes flaky annotation story with minor diff.
```
Error: Screenshot comparison failed:
5 pixels (ratio 0.01 of all image pixels) are different
Expected: /app/e2e/test_failures/annotations_stories-Annotations-stories-Hover--acf9e-her-annotations-when-rect-annotation-is-hovered-chrome/annotations-stories/hover-state/should-fade-all-other-annotations-when-rect-annotation-is-hovered-expected.png
Received: /app/e2e/test_failures/annotations_stories-Annotations-stories-Hover--acf9e-her-annotations-when-rect-annotation-is-hovered-chrome/annotations-stories/hover-state/should-fade-all-other-annotations-when-rect-annotation-is-hovered-actual.pn …
```

ci: fix flaky animation story

---

e2e/scripts/test.sh
e2e/tests/flame_stories.test.ts
packages/charts/src/chart_types/flame_chart/flame_chart.tsx
packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
packages/charts/src/chart_types/flame_chart/shaders.ts
packages/charts/src/common/kingly.ts
packages/charts/src/common/webgl_constants.ts

PR #1690 (`main` commit 67052711) introduced, among numerous other improvements, a conversion to the WebGL2-only uniform buffer objects. Its purpose was mere preparation for eventual WebGPU conversion, which doesn't have singular uniforms, only UBOs. However, certain hardware, OS and browser combinations (specifically, some older Intel MBPs with Chrome and Safari) were flaky with UBOs. As it represented additional code anyway, this PR removes it.
This PR also includes commits with minor WebGL code cleanup and start of documentation. 
Easiest to review commit by commit

fix(flame): undo the conversion to uniform buffer objects

---

.eslintignore

`eslint` got stuck if you have an e2e report locally (probably due to the minified/uglified nature of the generated code for the report).
This PR should fix that by ignoring that directory.

build: fix eslint got stuck on e2e reports

---

packages/charts/api/charts.api.md
packages/charts/src/chart_types/metric/renderer/dom/index.tsx
packages/charts/src/utils/themes/dark_theme.ts
packages/charts/src/utils/themes/light_theme.ts
packages/charts/src/utils/themes/theme.ts

Expose the metric min-height to enable scrollable behavior in Kibana.
fix #1788

feat(metric): expose min metric height

---

packages/charts/src/_reset.scss

We completely miss some reset CSS properties (like global font-family) that are available in the EUI legacy reset.
This PR will bring it back and restore the required style when importing elastic-charts only in a project without EUI.
I tried to import elastic-charts in an external project and the font used in the Metric viz wasn't the correct one.
With this PR I was able to bring back the fonts on such external project

fix(style): import the correct legacy reset css

---

packages/charts/src/chart_types/heatmap/state/selectors/get_cursor_band.ts

Match behavior of `externalPointerEvents.tooltip.visible` option on heatmap. Currently, heatmap external band will only show when this option is set to `true`.
The current heatmap tooltip is only visible when both a x and y values are valid, hence not on external events. This could be improved upon in the future to add a list of categories for a given `x` value. Showing just the x value would not serve any purpose.

fix(tooltip): heatmap visible tooltip option

---

jest.config.js

Latest ts-jest changes deprecated `globals` syntax, see [docs](https://kulshekhar.github.io/ts-jest/docs/getting-started/options/tsconfig/#path-to-a-tsconfig-file). This throws a warning when running tests, this updates to the latest config options.
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```

chore(jest): fix jest warning

---

packages/charts/src/chart_types/flame_chart/flame_api.ts
packages/charts/src/chart_types/flame_chart/flame_chart.tsx
packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
packages/charts/src/chart_types/flame_chart/render/draw_webgl.ts
packages/charts/src/chart_types/flame_chart/shaders.ts
playground/playground.tsx
storybook/stories/icicle/04_cpu_profile_gl_flame.story.tsx

Completes support for tweening node positions between `position0` -> `position1` and `size0` -> `size1`
The behavior is unchanged  if `columns.position0 === columns.position1 && columns.size0 === columns.size1`
This change allows the following functionality:
With node identities unchanged (meaning that the same node count is present, and the i-th node in both the `*0` and `*1` columns means the same entity: either the position, or size, or both can change. The tweening is currently linear, set to 500ms (as it can be a sweeping change).
If nodes would mismatch, for example, some nodes go away, while others are entered, with generally different node count between the start and target state:
1. Use the larger of the node count in all arrays; the superfluous entries will just get the …

feat(flame): node size and position tweening

---

packages/charts/src/common/kingly.ts

Fixes an apparent Firefox regression on Mac OS with Intel CPUs with a Firefox version on or before 106.0.5 but after 103.0.2. The browser issue itself is potential reportable browser infosec vulnerability, see the details.
The PR also converts most thrown errors to `Logger.warn` to be less draconian. Reporting still happens but erroneous or inconsequential issues won't prevent rendering.
Fixes https://github.com/elastic/elastic-charts/issues/1868
A Firefox version on or before 106.0.5 but after 103.0.2 introduced reporting `webgl_gl_VertexID_Offset` as a uniform, when querying `gl.ACTIVE_UNIFORMS` by `gl.getProgramParameter(program, GL.ACTIVE_UNIFORMS))`. While we use an *attribute*, called `gl_VertexID` that's implied into existence just by referencing it in the shader code (eg. it …

fix: workaround firefox amd macbook regression webgl_gl_VertexID_Offset

---

packages/charts/src/common/kingly.ts

Backports the following commits to 50.2.x:
- fix: workaround firefox amd macbook regression webgl_gl_VertexID_Offset (#1869)

fix: workaround firefox amd macbook regression webgl_gl_VertexID_Offset (#1869) [50.2.x]

---

packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts

Fixes cursor while dragging cursor when brushing is not available.
fix #1857 
fix #1882

fix(xy): cursor while dragging with no brushing

---

packages/charts/src/components/tooltip/tooltip.tsx

I've noticed the following error when trying to scroll a page with a chart:
```
TypeError: Cannot read properties of undefined (reading 'contains')
```
that was pointing to the `target.classList.contains('echTooltip__tableBody')` check in the `handleScroll` function of `tooltip.tsx`.
Checking the code seems that we ignore the possibility of the target being null, so I've added that check and ensured that the element has the `classList` property.
I don't have a reliable way to test this :(

fix(tooltip): check if scroll event target is null

---

jest.config.js
package.json
packages/charts/package.json
yarn.lock

Bumps the uuid version so that uuid does not trigger loading an ESM version via jest. This wasn't previously a problem for Kibana because we had previously implemented a custom resolver for Jest. I'm trying to remove it but the uuid dep in `@elastic/charts` is breaking that branch.

chore: update to uuid v9 for better exports support

---

.releaserc.js

Semantic-release doesn't have `main` in their default `branches` rule. Adding to allow releasing on this branch.
Solves the following error on release:
>This test run was triggered on the branch main, while semantic-release is configured to only publish from 38.0.x, 39.x, 40.0.x, 40.1.x, 40.x, 46.0.x, 49.x, 50.2.x, next, alpha, therefore a new version won’t be published.
See https://semantic-release.gitbook.io/semantic-release/usage/configuration and https://github.com/semantic-release/semantic-release/issues/1581

build: release on main branch

---

packages/charts/src/chart_types/partition_chart/layout/viewmodel/picked_shapes.ts

Fixes bug with incorrect `key` for `SeriesIdentifier` on the tooltip items.
In the alpha version of `Partition` charts we just set both the `key` and  `specId` of the `seriesIdentifier` to the `specId`. I believe later we added the proper `key` when working on partition changes to the legend and added the correct `key`, see snippet below for legend `key` value.
https://github.com/elastic/elastic-charts/blob/52c8a9eec3d1ee8cf8254c82ea6395790cb83f67/packages/charts/src/chart_types/partition_chart/layout/utils/legend.ts#L88-L99
Where the `key` is assigned the `dataName` value from the `QuadViewModel` item.
Unblocks https://github.com/elastic/kibana/issues/150304

fix(partition): tooltip item series identifier

---

packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/_annotations.scss
packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/line_marker.tsx

Annotations with no click handlers configured are no longer shown as interactive.
fix #1969

fix(annotation): render annotations correctly based on passed handlers

---

.buildkite/package.json
.buildkite/yarn.lock
github_bot/package.json
github_bot/yarn.lock
renovate.json

Downgrade the `json-schema-to-typescript` to avoid upgrade of transitive dependency `@bcherny/json-schema-ref-parser`. Removes `json-schema-to-typescript` from renovate config, no need to keep this library updated until upgrading and using new major of typescript features.

ci: fix release error with json-schema package

---

.buildkite/scripts/steps/eslint.ts
.buildkite/utils/exec.ts
.buildkite/utils/github.ts
packages/charts/src/chart_types/metric/renderer/dom/index.tsx

Fixes issue with ci linting check where the files to lint were not properly being passed to the `yarn lint:it` command, resulting in a noop execution.
Added group naming to differentiate running linting checks on all vs some files, removed unneeded code and comments.
I don't understand the usage of the `input` parameter on the [`execSync`](https://nodejs.org/api/child_process.html#child_processexecsynccommand-options) util, it works to pass the buildkite `json` pipeline but apparently not not to pass arguments to the command as I had thought. Fixed by adding `args` option to `exec` util to append `command`.
fixes #1823

ci: fix execSync input parameter

---

package.json
packages/charts/src/components/chart.tsx
yarn.lock

The redux dev tools are not actively used in ECH developments and our state needs to be sanitized before using them correctly. So for now I prefer to remove their usage from charts and bring it back when https://github.com/elastic/elastic-charts/issues/2078 is fixed.

fix: remove unused redux dev tools

---

packages/charts/src/components/chart_status.tsx

This increases the accuracy of when we report render changes to account for asynchronous render operations.
Fix https://github.com/elastic/elastic-charts/issues/2124

fix: Wait a tick before reporting render status

---

packages/charts/src/chart_types/xy_chart/axes/timeslip/continuous_time_rasters.ts

'substr' is just as fine as it's string specific and well named. but it was deprecated. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
Therefore, I changed the code to use String.prototype.substring() instead of String.prototype.substr().

chore: convert `substr` to `substring`

---

packages/charts/src/common/default_theme_attributes.ts

Updating the font family to match the EUI one.
fix https://github.com/elastic/elastic-charts/issues/2149

fix: update font family

---

packages/charts/src/chart_types/xy_chart/annotations/rect/dimensions.ts
packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts

Now axes `tickLine` are always rendered unless `visible` is `false`, thereby including the `tickLine.padding` even if the `tickLine.size` or `tickLine.strokeWidth` are `0`.
**BREAKING CHANGE:** Now displays `padding` where before would be hidden possibly creating an inadvertent breaking style change.
> Notice the bottom axes, as the `tickLine.size` goes to `0` the padding does not get removed.
This logic was added back in #711 with a complete overhall of the axes logic. This was added to render only things that absolutely needed to be rendered and a `0` `length` or `strokeWidth` line does not. However this would unexpectedly strip away the `tickLine.padding` even with the `tickLine.visible` set to `true`. This change should have minimal impact across kibana but better to perform this …

fix(axis): always render `tickLine` unless `visible` is `false`

---

packages/charts/src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts

Clamps the `min` scaled value on the brushing event to the max bucket value when `allowBrushingLastHistogramBin` is set to `false`.
Leaving the `min` value unclamped would allow the value to exceed the last bucket starting value.
fix #2224

fix: clamp brushing min of last bucket

---

e2e/page_objects/common.ts
e2e/tests/tooltip.test.ts
e2e_server/server/generate/vrt_page_template.js
e2e_server/server/mocks/use_global_parameters.ts
storybook/stories/metric/1_basic.story.tsx
storybook/stories/test_cases/11_resize_debounce.story.tsx
storybook/story_wrapper.tsx
storybook/style.scss
storybook/types.ts

We've started adding `resize` wrapper elements around certain stories to allow for a better size per chart while also allowing the docs consumer to easily resize the chart to see how it changes.
This caused a bit of an issue in #2156 with clipping of the vrt screenshots.
This PR adds a `resize` config to the `Story.parameters`. This allows us to pass a `boolean` where if true we wrap the story in resizable `div`, matching the default size of the `.echChart`. You may also pass this parameter any css styles to be applied to this resize wrapper. For example the `Metric - Basic` story just adds the following to override the `height` and `width` of the resize wrapper to `200px`.
```tsx
Example.parameters = {
resize: {
height: '200px',
width: '200px',
},
};
```
Any provided styles override the …

test: add resize config for easy story and e2e resizing

---

storybook/style.scss

Fixes issues related to clipping of screenshot in vrt setup.
When we improved the tooltip placement logic we added styles to the e2e specific server. We added padding on the top and bottom of the chart to allow the tooltip to be unencumbered by the surrounding container to avoid unexpectedly pushing the tooltip into only the visible chart space.
But we recently have added charts with `resize` that are set to a greater height such that the top padding plus the height of the chart is greater than the playwright viewport, thus clipping the bottom of the chart in the screenshots.

ci: fix vrt-specific style issues

---

packages/charts/src/utils/themes/legacy_dark_theme.ts
packages/charts/src/utils/themes/legacy_light_theme.ts
packages/charts/src/utils/themes/theme_common.ts

Backports the following commits to 61.0.x:
- fix(theme): legacy margins (#2262)

fix(theme): legacy margins (#2262) [61.0.x]

---

packages/charts/src/chart_types/partition_chart/layout/utils/treemap.ts
packages/charts/src/chart_types/partition_chart/partition.test.tsx

Backports the following commits to 60.x:
- fix(partition): zero value sectors cause max stack call (#2260)

fix(partition): zero value sectors cause max stack call (#2260) [60.x]

---

packages/charts/src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts

Backports the following commits to 60.x:
- fix: clamp brushing min of last bucket (#2227)

fix: clamp brushing min of last bucket (#2227) [60.x]

---

packages/charts/api/charts.api.md
packages/charts/src/chart_types/partition_chart/layout/viewmodel/hierarchy_of_arrays.ts
packages/charts/src/chart_types/xy_chart/legend/legend.test.ts
packages/charts/src/chart_types/xy_chart/legend/legend.ts
packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
packages/charts/src/common/legend.ts
packages/charts/src/components/legend/extra.tsx
packages/charts/src/components/legend/legend_item.tsx
packages/charts/src/components/legend/utils.ts
packages/charts/src/specs/settings.tsx

Expose both the formatted and the raw value in the legend extra.
The extra value in the legendItem has now the following shape:
```ts
extraValue?: {
raw: PrimitiveValue;
formatted: string;
};
```
A `CustomLegend.item` now receive an extra value in the form of `{raw: PrimitiveValue;formatted: string;}`

feat(legend): expose extra raw values

---

packages/charts/src/components/portal/tooltip_portal.tsx
packages/charts/src/components/tooltip/tooltip.tsx
packages/charts/src/state/selectors/get_tooltip_settings.ts

Fixes performance issue notice with synced tooltips.
The `popperSettings` value here...
https://github.com/elastic/elastic-charts/blob/48cade4b42e873ab9dcac88b958f29ef35298a0b/packages/charts/src/components/tooltip/tooltip.tsx#L150-L167
...was triggering an update for every new render even though the settings values had not changed.
This was caused by the `getTooltipSettings` helper method here...
https://github.com/elastic/elastic-charts/blob/48cade4b42e873ab9dcac88b958f29ef35298a0b/packages/charts/src/components/tooltip/tooltip.tsx#L332-L343
...which was returning a new merged instance of the settings for every external event.
fixes #2309

perf(tooltip): improve placement logic

---

storybook/stories/legend/16_custom_legend.story.tsx

Fix error in custom legend story where the legend `extraValue` is passed as React node, but it instead is an object that can't be rendered directly.

docs: fix custom legend story

---

packages/charts/api/charts.api.md
packages/charts/src/chart_types/bullet_graph/chart_state.tsx
packages/charts/src/chart_types/bullet_graph/renderer/canvas/index.tsx
packages/charts/src/chart_types/bullet_graph/selectors/get_debug_state.ts
packages/charts/src/chart_types/bullet_graph/selectors/get_panel_dimensions.ts
packages/charts/src/index.ts
packages/charts/src/state/types.ts
storybook/stories/bullet_graph/1_single.story.tsx
storybook/stories/bullet_graph/6_grid.story.tsx
storybook/stories/goal/2_gauge_with_target.story.tsx

Adds `debugState` for `Bullet` charts under the `bullet` property of `DebugState`.

fix(bullet): add a11y summary and debugState

---

packages/charts/src/components/_global.scss
packages/charts/src/components/legend/_legend.scss
storybook/stories/legend/16_custom_legend.story.tsx

Fixes an issue causing the legend to be placed behind the `.echChartBackground` element.
The `.echChartBackground` element had no `z-index` applied which causes any custom legend to be covered by the background.
fix #2363

fix(legend): custom legend covered by background

---

packages/charts/src/chart_types/metric/renderer/_index.scss
packages/charts/src/chart_types/metric/renderer/dom/_text.scss
packages/charts/src/chart_types/metric/renderer/dom/text.tsx

Closes: https://github.com/elastic/observability-dev/issues/3430
Closes: https://github.com/elastic/observability-dev/issues/3391
When we use the `Metric Chart` in `Kibana`, we have a problem where the focus halo is shown twice. I think we can explicitly add the property `outline: none`; to the `echMetricText__title button` to resolve this issue

fix(Metric): Cards should only show one focus halo on `::focus` event

---

packages/charts/src/chart_types/xy_chart/utils/series.test.ts
packages/charts/src/chart_types/xy_chart/utils/series.ts

This PR reduces the noise generated in the console logs by passing non-numerical values as Y values in cartesian charts when in development mode.

chore: reduce non-numeric number noise in logs

---

packages/charts/src/chart_types/flame_chart/flame_chart.tsx

Fixes issue where the `Flame` chart was attempting to access [`window.visualViewport`](https://developer.mozilla.org/en-US/docs/Web/API/Window/visualViewport) from within an iframe.
The `Flame` chart was attempting to access the [`window.visualViewport`](https://developer.mozilla.org/en-US/docs/Web/API/Window/visualViewport) of the top most `window` from an iframe. However this triggered a `DOMException` error as the `visualViewport` property is forbidden expect when accessed by the top `window` context, for cross-origins.
```
DOMException: Failed to read a named property 'visualViewport' from 'Window': Blocked a frame with origin "https://my.kibana.com" from accessing a cross-origin frame.
```
We were only updating this value every `100ms` to capture the latest `pinchZoomScale`. Since …

fix(flame): failure when accessing `visualViewport.visualViewport` from within `iFrame`

---

packages/charts/src/components/tooltip/components/_tooltip_actions.scss

👋 Hey y'all! I'm cleaning up some Sass exports (specifically of component-specific variables) in EUI's public exports and noticed this one variable usage that has no other usages in Kibana or Cloud. I'm switching it to a more generic equivalent that should not cause any UI regressions within the Amsterdam theme.
For the full list of mixins/variables being removed, see https://github.com/elastic/eui/pull/8031

style: Remove EUI Sass component-specific variable

---

packages/charts/src/specs/specs_parser.test.tsx
packages/charts/src/state/chart_state.ts

A [PR in Kibana](https://github.com/elastic/kibana/pull/193798) identified a bug in our current code (and probably also in the ResizeObserver API). This PR showed that the ResizeObserver can dispatch the same witdh/height/left/top values under certain circumstances (not really clear from the PR).
In code we don't have a check for this case thus a duplicated `updateParentDimension` action can be dispatched causing the chart to remain in a wrong state: the `renderedComplete:false` but the chart still rendered on the screen. The configured chart renderer doesn't get triggered because the parentDimension in effect is not changed, thus the render count doesn't increase and no dispatch to `onRenderComplete`is issued, causing a wrong ChartStatus to be reported.
The fix just trigger a …

fix(ChartStatus): render complete if same parent size is dispatched

---

docs/docs/api/specs/xy/line_annotation.mdx
packages/charts/api/charts.api.md
packages/charts/src/chart_types/xy_chart/specs/line_annotation.ts
packages/charts/src/chart_types/xy_chart/utils/specs.ts

Removes unused `hideLinesTooltips` prop on `LineAnnotationSpec` that was left unused after #418

chore: remove unused `hideLinesTooltips` prop on `LineAnnotationSpec`

---

packages/charts/src/components/chart.tsx
packages/charts/src/state/selectors/chart_container_updates.ts
packages/charts/src/state/selectors/get_internal_can_display_chart_titles.ts

The `Chart` component `render` function is called everytime something change in the redux store (for example every time you move the mouse over the chart).
This is well visible if you add a  console.log in the render method of the `Chart` component and move the mouse over the chart.
This PR  avoids that rendering by moving some store-subscribed logic into re-selectors.

perf: fix unnecessary re-render

---

packages/charts/api/charts.api.md
packages/charts/src/index.ts
packages/charts/src/utils/themes/get_charts_theme.ts

The new Borealis theme introduced a theme-aware and darkMode-aware theming. Charts however only exports 2 themes based only on darkMode. Rather than export 4 themes and having the user pick the correct one, I created a util that accepts either the `CoreTheme` definition from kibana, or the `UseEuiTheme` type from eui.
```ts
// Kibana theme
import { DARK_THEME, LIGHT_THEME } from '@elastic/charts';
const coreTheme = { name: 'amsterdam', darkMode: false };
const chartsTheme = coreTheme.darkMode ? DARK_THEME : LIGHT_THEME;
// Eui theme
import { useEuiTheme } from '@elastic/eui';
const euiTheme = useEuiTheme();
const chartsTheme = coreTheme.colorMode === 'DARK' ? DARK_THEME : LIGHT_THEME;
```
```ts
// Kibana theme
import { getChartsTheme } from '@elastic/charts';
const coreTheme = { name: …
```

chore: add util for getting charts theme based on eui theme/colorMode

---

packages/charts/api/charts.api.md
packages/charts/src/index.ts
packages/charts/src/utils/themes/base_colors.ts
packages/charts/src/utils/themes/dark_theme.ts
packages/charts/src/utils/themes/light_theme.ts
packages/charts/src/utils/themes/theme.ts

Remove remaining Amsterdam colors, using their hex code until https://github.com/elastic/elastic-charts/issues/2601 is done.
BREAKING CHANGE: the light and dark themes follow the EUI Borealis theme.

style(theme): cleanup remaining theme changes

---

packages/charts/api/charts.api.md
packages/charts/src/index.ts
packages/charts/src/utils/themes/amsterdam_dark_theme.ts
packages/charts/src/utils/themes/amsterdam_light_theme.ts
packages/charts/src/utils/themes/get_charts_theme.ts

Backports the following commits to 69.0.x:
- fix(themes): reintroduce Amsterdam colors (#2604)

fix(themes): reintroduce Amsterdam colors (#2604) [69.0.x]

---

.releaserc.js

I've cleaned a but the semantic-release configuration giving a simplified version of the dry-run command.
Before that change you need 3 tokens in your ENV to make it pass with different permissions.
I don't see a reason to run these checks locally because the tokens are different from the one in the CI, so I've reduced the dry-run steps to only execute the `commit-analyzer` and the `release-notes-generator`. These two are enough to understand if the current commits are correctly configured and what will be the output of the CHANGELOG.

build: release dry-run only runs commit analyzer

---

.buildkite/package.json
.buildkite/yarn.lock

Backports the following commits to 69.x:
- build(deps): bump axios from 1.7.4 to 1.8.2 in /.buildkite (#2624)

build(deps): bump axios from 1.7.4 to 1.8.2 in /.buildkite (#2624) [69.x]

---

github_bot/package.json
github_bot/yarn.lock

Backports the following commits to 69.x:
- build(deps): bump axios from 1.6.0 to 1.8.2 in /github_bot (#2626)

build(deps): bump axios from 1.6.0 to 1.8.2 in /github_bot (#2626) [69.x]

---

packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx

fix: Sparkline svg `aria-labelledby` now generates a valid ID that will make Metric charts more accessible.
This patch would modify the `aria-labelledby` attribute that is generated for the svg rendered by the Sparkline component within the Metric chart type. Downstream in Kibana we are failing an accessibility audit because our metrics charts do not contain `alt` or `aria` for this SVG. We can allow the svg to be described by an existing element that contains a proper label for the chart, but the `aria-labelledby` contains a space, which is not valid for this attribute and causes the attempt to link up an element ID to fail.
**Before (from [hosted storybook](https://elastic.github.io/elastic-charts/storybook/?path=/story/metric-alpha--basic&globals=toggles.showHeader:true;toggles.showChar …

fix: Update aria-labelledby for Sparkline svg to not use spaces

---

e2e/tests/tooltip.test.ts

Skips some flaky e2e tooltip tests. The size of the tooltips isn't consistent so the visual regression tests don't pass from time to time.

chore: skip flaky tooltip tests

---

.buildkite/package.json
.buildkite/pipelines/pull_request/pipeline.sh
.buildkite/utils/pipeline/steps.ts
catalog-info.yaml

This PR adds a `catalog-info.yaml` through which a new pipeline can be created in the shared elastic infrastructure.
The PR also adds a branching logic, so that the pipeline will work more or less identical on the new infrastructure. The changes required for this are: 
- emit to `stdout` instead of uploading steps - the runner will run the pipeline file, and upload the resulting string
- use different agent targeting rules - there aren't agent-queues on the new infra, like we had in Kibana-buildkite
Once this PR is merged, Terrazzo will pick up the changes, create the pipeline, and the two pipelines can live parallel to each other, while we're testing. If we're happy with the pipeline, we can work on triggering and if we need to keep history of the previous job.
Doesn't fix it just yet, …

chore(ci): Migrate to Elastic-wide Buildkite infra
