src/components/react_canvas/axis.tsx

fix(axis): account for title padding in horizontal title positioning

---

src/lib/utils/dimensions.ts

fix(dimensions): use chart top padding in computation of chart height

---

.travis.yml
package.json

Adding the `--ci` flag on deploy and fix publishing on npm org

build(storybook): fix ci storybook deploy

---

src/lib/axes/canvas_text_bbox_calculator.ts

fix(offscreen canvas): set negative position to move offscreen

---

src/lib/utils/domain.test.ts

Fills in missing coverage for this file, bringing test coverage up from 52.63% to 100% 😄 

test(utils/domain): add tests for domain computations

---

package.json
stories/interactions.tsx
tsconfig.all.json

This PR add a ts checks also on typescript stories to avoid having a broken master. 

Add stories ts check on commit and build

---

.storybook/config.ts
src/state/chart_state.ts

This PR remove some wrong configuration of storybook and some console.logs introduced by #153

docs: fix storybook missing stories

---

src/specs/settings.test.tsx

Add test coverage for `SettingsComponent`. 
~- [] Proper documentation or storybook story was added for features that require explanation or tutorials~

test(settings): add coverage for spec mount & update

---

src/index.ts
stories/annotations.tsx
stories/interactions.tsx

There were some missing exports from the annotation feature. This add the missing class/functions to the main index.ts

fix(exports): fix missing exports for annotations

---

package.json
yarn.lock

Update EUI dependency to 11.0.0

fix(eui): update EUI dependency to 11.0.0

---

tsconfig.json

Update the build target to ES5

fix(build): change build target to ES5

---

tsconfig.json

Change the module resolution to `commonjs`
- ~~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~~
- ~~[ ] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)~~

fix(build): compile module resolution in commonjs

---

src/components/legend/legend.tsx

I'll take the blame on this one 🙋‍♂ 😞

chore: remove rogue console.log

---

package.json

Update node engine to `>=10`
closes #359

build(remove engine): remove node engine and commitizen dep

---

wiki/consuming.md

Add required polyfills
closes #371

docs: update polyfill info in consuming doc

---

CHANGELOG.md

Correct errors in release notes written to `CHANGELOG.md`

chore: correct changelog

---

src/utils/themes/theme.ts

Update Bar, Line and Area, theme docs to reflect global use of theme style
closes #383

docs(theme): update theme styles with clarifying explaination

---

.ci/jobs/defaults.yml

Change visual regression image diff directory

ci: update gcs file pattern

---

src/chart_types/xy_chart/legend/legend.test.ts
src/chart_types/xy_chart/legend/legend.ts
src/chart_types/xy_chart/rendering/rendering.test.ts
src/chart_types/xy_chart/store/__snapshots__/utils.test.ts.snap
src/chart_types/xy_chart/store/chart_state.test.ts
src/chart_types/xy_chart/store/utils.test.ts
src/chart_types/xy_chart/store/utils.ts
src/chart_types/xy_chart/tooltip/tooltip.ts
src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
src/chart_types/xy_chart/utils/series.ts
src/chart_types/xy_chart/utils/specs.ts
src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
src/chart_types/xy_chart/utils/stacked_series_utils.ts
src/components/legend/legend.tsx
stories/area_chart.tsx

Reverts elastic/elastic-charts#398
Bad naming

Revert "Feat/banded legend values"

---

.github/semantic.yml

Configure semantic PR bot to check only PR titles

build(github): configure semantic pull request bot

---

.ci/run.sh
package.json

ci: update ci to enforce yarn.lock sync

---

package.json

Added `utility-types` as dependency

fix: add utility-types as dependency

---

package.json

Add script to `package.json` for backporting.

chore: add backport script

---

src/chart_types/partition_chart/state/selectors/geometries.ts
src/chart_types/partition_chart/state/selectors/scenegraph.ts

fix: remove log

---

package.json
src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/axis.tsx
src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/bar_values.tsx
src/chart_types/xy_chart/renderer/canvas/grid.tsx
src/chart_types/xy_chart/renderer/canvas/line_annotation.tsx
src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
src/chart_types/xy_chart/renderer/canvas/rect_annotation.tsx
src/chart_types/xy_chart/specs/line_annotation.tsx
src/components/chart_container.tsx
src/components/icons/assets/dot.tsx
src/components/icons/icon.tsx
src/components/legend/legend_item.tsx
src/components/react_canvas/grid.tsx
yarn.lock

Backports the following commits to 16.1.x:
- fix: replace PureComponent with shouldComponentUpdate (#534)

fix: replace PureComponent with shouldComponentUpdate (#534)

---

src/chart_types/xy_chart/annotations/line_annotation_tooltip.ts
src/chart_types/xy_chart/utils/axis_utils.test.ts
src/chart_types/xy_chart/utils/axis_utils.ts
src/chart_types/xy_chart/utils/series.ts

Very quick code cleanup, removing one unused function and avoid few export.

refactor: remove unused function and exports

---

CONTRIBUTING.md

Updated docs to share how to link the library to kibana and other applications.
(https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)

docs: add linking steps to CONTRIBUTING.md

---

.ci/jobs/elastic+elastic-charts+pull-request.yml

Fixing the jobs status-context

ci: fix status context

---

.ci/jobs/elastic+elastic-charts+pr-license-scan.yml
.ci/jobs/elastic+elastic-charts+pr-lint.yml
.ci/jobs/elastic+elastic-charts+pr-unit-tests.yml
.ci/jobs/elastic+elastic-charts+pr-vrts.yml

ci: fix git refspec

---

.playground/playground.tsx
src/chart_types/heatmap/layout/viewmodel/viewmodel.ts

Filter out highlighted data based on presented Y values

fix: filter highlighted Y values

---

.eslintrc.js

Fix double comma `--fix` issue

ci: fix comma linting

---

stories/goal/2_gauge_with_target.tsx

Add few knobs to a radial gauge charts to le the user play a bit

docs: add more knobs to gauge stories

---

.github/workflows/auto_release.yaml

build: update release workflow

---

api/charts.api.md
src/chart_types/heatmap/specs/heatmap.ts
src/chart_types/heatmap/specs/index.ts
src/chart_types/partition_chart/layout/types/viewmodel_types.ts
src/chart_types/partition_chart/layout/utils/group_by_rollup.ts
src/index.ts

Export some missing types used in Kibana but not exported from the main module

fix: missing exported types

---

FAQ.md
README.md

Updates FAQ & README to reflect #1242

docs(readme): update README and FAQ

---

storybook/webpack.config.js

Fix storybook `source-loader` error

build: fix storybook build source error

---

.releaserc.js
integration/jest_puppeteer.config.js
package.json
packages/charts/package.json
packages/charts/scripts/move_txt_files.js

This should fix the missing `package.json` in the commit message done by semantic-release.

chore: fix semantic-release git commit

---

.releaserc.js
package.json
packages/charts/scripts/move_txt_files.js

Trying to add the CHANGELOG, LICENSE, NOTICE and README files into the published package

fix: add LICENSE file into the published package

---

.github/pull_request_template.md

Checklist is rewritten, adding dark mode + theme changes checks

docs: update the PR checklist

---

.github/workflows/ci.yaml

Prevent triggering push and pull_request ci jobs on the same pull request.

ci: fix action triggers

---

storybook/main.js

Fix storybook hot reloading issues.

docs(storybook): fix hot reloading

---

.ci/global_setup.sh
.github/workflows/ci.yaml
.github/workflows/release.yaml

These changes were removed while testing #1404 and got auto merged 🤷🏼‍♂️ 😅 
@markov00 is there a way to verify this is working in jenkins?

ci: add back puppeteer skip download flag

---

packages/charts/api/charts.api.md
packages/charts/src/state/selectors/get_chart_theme.ts
packages/charts/src/utils/common.test.ts
packages/charts/src/utils/common.ts
packages/charts/src/utils/themes/merge_utils.ts

Backports the following commits to 38.0.x:
- fix(theme): merge partial with empty initial partial (#1452)

fix(theme): merge partial with empty initial partial (#1452) [38.0.x]

---

packages/charts/src/chart_types/xy_chart/renderer/dom/cursor_band.tsx
packages/charts/src/chart_types/xy_chart/renderer/dom/cursor_crossline.tsx
packages/charts/src/chart_types/xy_chart/renderer/dom/cursor_line.tsx
packages/charts/src/chart_types/xy_chart/state/chart_state.tsx
packages/charts/src/components/__snapshots__/chart.test.tsx.snap

Backports the following commits to 38.0.x:
- fix(interactions): line cursor above the chart, band cursor below (#1453)

fix(interactions): line cursor above the chart, band cursor below (#1453) [38.0.x]

---

.github/ISSUE_TEMPLATE/bug_report.md

A slight adjustment to the bug template

docs: update bug template

---

CONTRIBUTING.md

Update docs for linking charts to kibana

docs: update linking steps

---

storybook/stories/composable/1_basic.story.tsx

This PR fixes the mouse events not working nicely in the composable story

fix(example): make events work in the composable story

---

.buildkite/package.json
.buildkite/yarn.lock
github_bot/package.json
github_bot/yarn.lock

Removing an unused buildkite library

chore(deps): remove elastic/kibana-buildkite-library dependency

---

lerna.json
package.json
yarn.lock

This update should fix some dependency security issues raised by Github dependabot

chore(deps): Update lerna to 5.x

---

README.md

I updated the [consuming] link to point to the right wiki URL https://github.com/elastic/elastic-charts/wiki/Consuming-@elastic-charts

fix: update broken wiki links

---

packages/charts/src/chart_types/heatmap/state/selectors/on_element_click_caller.ts
packages/charts/src/utils/common.tsx

A valuable's property is accessed without null check. 
This patch fixes incorrect conditions and removes unnecessary code.

refactor: improve condition statements

---

e2e_server/server/webpack.config.js
package.json
storybook/webpack.config.js
yarn.lock

This commit fixes the EUI dependency that cause some trouble when building with webpack 4.

build: fix EUI dependency

---

.github/workflows/release.yaml

Updated `release.yml` workflow dependencies to resolve errors.

ci: update release workflow deps

---

e2e/tests/performance.test.ts

It reduced the measurement threshold in the performance test.

test(perf): fix reduce performance measure threshold

---

packages/charts/src/chart_types/xy_chart/utils/fill_series.ts
packages/charts/src/chart_types/xy_chart/utils/series.ts

Clean up a bit the code, reducing the number of loops and object creation

refactor(xy): cleaup loops

---

packages/charts/api/charts.api.md
packages/charts/src/index.ts
packages/charts/src/utils/themes/amsterdam_dark_theme.ts
packages/charts/src/utils/themes/amsterdam_light_theme.ts
packages/charts/src/utils/themes/get_charts_theme.ts

Reintroduce Amsterdam colors to be used along side with Legacy Amsterdam EUI theme.

fix(themes): reintroduce Amsterdam colors
